// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.31.1
// source: apis/group/group.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types.group";

/** GroupMember */
export interface GroupMember {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"role" */
  role: number;
  /** @gotags: json:"nickname" */
  nickname: string;
  /** @gotags: json:"mute_until" */
  mute_until: number;
  /** @gotags: json:"joined_at" */
  joined_at: number;
  /** @gotags: json:"extra" */
  extra: string;
}

/** Group */
export interface Group {
  /** @gotags: json:"id" */
  id: number;
  /** @gotags: json:"name" */
  name: string;
  /** @gotags: json:"avatar" */
  avatar: string;
  /** @gotags: json:"owner_id" */
  owner_id: number;
  /** @gotags: json:"notice" */
  notice: string;
  /** @gotags: json:"join_type" */
  join_type: number;
  /** @gotags: json:"member_count" */
  member_count: number;
  /** @gotags: json:"created_at" */
  created_at: number;
  /** @gotags: json:"updated_at" */
  updated_at: number;
}

/** GroupRequest */
export interface GroupRequest {
  /** @gotags: json:"id" */
  id: number;
  /** @gotags: json:"sender_id" */
  sender_id: number;
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"apply_msg" */
  apply_msg: string;
  /** @gotags: json:"status" */
  status: number;
  /** @gotags: json:"handler_id,omitempty" */
  handler_id: number;
  /** @gotags: json:"request_time" */
  request_time: number;
  /** @gotags: json:"handle_time" */
  handle_time: number;
  /** @gotags: json:"reject_reason,omitempty" */
  reject_reason: string;
}

/** CreateGroupReq */
export interface CreateGroupReq {
  /** @gotags: json:"name" */
  name: string;
  /** @gotags: json:"avatar,optional" */
  avatar: string;
  /** @gotags: json:"member_ids,optional" */
  member_ids: number[];
}

/** CreateGroupResp */
export interface CreateGroupResp {
  /** @gotags: json:"data" */
  data: Group | undefined;
}

/** GetGroupReq */
export interface GetGroupReq {
  /** @gotags: form:"group_id,optional" json:"group_id,optional" */
  group_ids: number[];
  /** @gotags: form:"name_keyword,optional" json:"name_keyword,optional" */
  name_keyword: string;
  /** @gotags: form:"limit,optional,default=30" json:"limit,optional,default=30" */
  limit: number;
  /** @gotags: form:"offset,optional,default=0" json:"offset,optional,default=0" */
  offset: number;
}

/** GetGroupMembersReq */
export interface GetGroupMembersReq {
  /** @gotags: form:"group_id" json:"group_id,optional" */
  group_id: number;
}

/** GetGroupMembersResp */
export interface GetGroupMembersResp {
  /** @gotags: json:"data" */
  data: GroupMember[];
}

/** GetGroupResp */
export interface GetGroupResp {
  /** @gotags: json:"data" */
  data: Group[];
  /** @gotags: json:"total" */
  total: number;
}

/** UpdateGroupReq */
export interface UpdateGroupReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"name,optional" */
  name: string;
  /** @gotags: json:"avatar,optional" */
  avatar: string;
  /** @gotags: json:"notice,optional" */
  notice: string;
  /** @gotags: json:"join_type,optional" */
  join_type: number;
}

/** JoinGroupReq */
export interface JoinGroupReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"message,optional" */
  message: string;
}

/** JoinGroupResp */
export interface JoinGroupResp {
  /** @gotags: json:"data,omitempty" */
  data:
    | GroupRequest
    | undefined;
  /** @gotags: json:"member,omitempty" */
  member: GroupMember | undefined;
}

/** HandleGroupApplyReq */
export interface HandleGroupApplyReq {
  /** @gotags: json:"apply_id" */
  apply_id: number;
  /** @gotags: json:"result" */
  result: number;
  /** @gotags: json:"reject_reason,optional" */
  reject_reason: string;
}

export interface HandleGroupApplyResp {
  /** @gotags: json:"data" */
  data: GroupRequest | undefined;
}

/** InviteMembersReq */
export interface InviteMembersReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"member_ids" */
  member_ids: number[];
}

/** InviteMembersResp */
export interface InviteMembersResp {
  /** @gotags: json:"success_count" */
  success_count: number;
  /** @gotags: json:"failed_ids,omitempty" */
  failed_ids: number[];
}

/** RemoveMemberReq */
export interface RemoveMemberReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"operator_id" */
  operator_id: number;
}

/** LeaveGroupReq */
export interface LeaveGroupReq {
  /** @gotags: json:"group_id" */
  group_id: number;
}

/** DismissGroupReq */
export interface DismissGroupReq {
  /** @gotags: json:"group_id" */
  group_id: number;
}

/** SetMemberRoleReq */
export interface SetMemberRoleReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"role" */
  role: number;
  /** @gotags: json:"operator_id" */
  operator_id: number;
}

/** SetMemberNicknameReq */
export interface SetMemberNicknameReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"nickname" */
  nickname: string;
}

/** MuteMemberReq */
export interface MuteMemberReq {
  /** @gotags: json:"group_id" */
  group_id: number;
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"mute_until" */
  mute_until: number;
}

/** GetUserGroupsReq */
export interface GetUserGroupsReq {
}

/** GetUserGroupsResp */
export interface GetUserGroupsResp {
  /** @gotags: json:"data" */
  data: number[];
}

/** GetPendingAppliesReq */
export interface GetPendingAppliesReq {
}

/** GetPendingAppliesResp */
export interface GetPendingAppliesResp {
  /** @gotags: json:"data" */
  data: GroupRequest[];
}

function createBaseGroupMember(): GroupMember {
  return { group_id: 0, user_id: 0, role: 0, nickname: "", mute_until: 0, joined_at: 0, extra: "" };
}

export const GroupMember: MessageFns<GroupMember> = {
  encode(message: GroupMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.user_id !== 0) {
      writer.uint32(16).uint64(message.user_id);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    if (message.nickname !== "") {
      writer.uint32(34).string(message.nickname);
    }
    if (message.mute_until !== 0) {
      writer.uint32(40).int64(message.mute_until);
    }
    if (message.joined_at !== 0) {
      writer.uint32(48).int64(message.joined_at);
    }
    if (message.extra !== "") {
      writer.uint32(58).string(message.extra);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.mute_until = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.joined_at = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.extra = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupMember {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      role: isSet(object.role) ? globalThis.Number(object.role) : 0,
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      mute_until: isSet(object.muteUntil)
        ? globalThis.Number(object.muteUntil)
        : isSet(object.mute_until)
        ? globalThis.Number(object.mute_until)
        : 0,
      joined_at: isSet(object.joinedAt)
        ? globalThis.Number(object.joinedAt)
        : isSet(object.joined_at)
        ? globalThis.Number(object.joined_at)
        : 0,
      extra: isSet(object.extra) ? globalThis.String(object.extra) : "",
    };
  },

  toJSON(message: GroupMember): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.role !== 0) {
      obj.role = Math.round(message.role);
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.mute_until !== 0) {
      obj.muteUntil = Math.round(message.mute_until);
    }
    if (message.joined_at !== 0) {
      obj.joinedAt = Math.round(message.joined_at);
    }
    if (message.extra !== "") {
      obj.extra = message.extra;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupMember>, I>>(base?: I): GroupMember {
    return GroupMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupMember>, I>>(object: I): GroupMember {
    const message = createBaseGroupMember();
    message.group_id = object.group_id ?? 0;
    message.user_id = object.user_id ?? 0;
    message.role = object.role ?? 0;
    message.nickname = object.nickname ?? "";
    message.mute_until = object.mute_until ?? 0;
    message.joined_at = object.joined_at ?? 0;
    message.extra = object.extra ?? "";
    return message;
  },
};

function createBaseGroup(): Group {
  return {
    id: 0,
    name: "",
    avatar: "",
    owner_id: 0,
    notice: "",
    join_type: 0,
    member_count: 0,
    created_at: 0,
    updated_at: 0,
  };
}

export const Group: MessageFns<Group> = {
  encode(message: Group, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.avatar !== "") {
      writer.uint32(26).string(message.avatar);
    }
    if (message.owner_id !== 0) {
      writer.uint32(32).uint64(message.owner_id);
    }
    if (message.notice !== "") {
      writer.uint32(42).string(message.notice);
    }
    if (message.join_type !== 0) {
      writer.uint32(48).int32(message.join_type);
    }
    if (message.member_count !== 0) {
      writer.uint32(56).int32(message.member_count);
    }
    if (message.created_at !== 0) {
      writer.uint32(64).int64(message.created_at);
    }
    if (message.updated_at !== 0) {
      writer.uint32(72).int64(message.updated_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Group {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.owner_id = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.join_type = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.member_count = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.created_at = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.updated_at = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Group {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      owner_id: isSet(object.ownerId)
        ? globalThis.Number(object.ownerId)
        : isSet(object.owner_id)
        ? globalThis.Number(object.owner_id)
        : 0,
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
      join_type: isSet(object.joinType)
        ? globalThis.Number(object.joinType)
        : isSet(object.join_type)
        ? globalThis.Number(object.join_type)
        : 0,
      member_count: isSet(object.memberCount)
        ? globalThis.Number(object.memberCount)
        : isSet(object.member_count)
        ? globalThis.Number(object.member_count)
        : 0,
      created_at: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updated_at: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
    };
  },

  toJSON(message: Group): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.owner_id !== 0) {
      obj.ownerId = Math.round(message.owner_id);
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    if (message.join_type !== 0) {
      obj.joinType = Math.round(message.join_type);
    }
    if (message.member_count !== 0) {
      obj.memberCount = Math.round(message.member_count);
    }
    if (message.created_at !== 0) {
      obj.createdAt = Math.round(message.created_at);
    }
    if (message.updated_at !== 0) {
      obj.updatedAt = Math.round(message.updated_at);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Group>, I>>(base?: I): Group {
    return Group.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Group>, I>>(object: I): Group {
    const message = createBaseGroup();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.avatar = object.avatar ?? "";
    message.owner_id = object.owner_id ?? 0;
    message.notice = object.notice ?? "";
    message.join_type = object.join_type ?? 0;
    message.member_count = object.member_count ?? 0;
    message.created_at = object.created_at ?? 0;
    message.updated_at = object.updated_at ?? 0;
    return message;
  },
};

function createBaseGroupRequest(): GroupRequest {
  return {
    id: 0,
    sender_id: 0,
    group_id: 0,
    apply_msg: "",
    status: 0,
    handler_id: 0,
    request_time: 0,
    handle_time: 0,
    reject_reason: "",
  };
}

export const GroupRequest: MessageFns<GroupRequest> = {
  encode(message: GroupRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.sender_id !== 0) {
      writer.uint32(16).uint64(message.sender_id);
    }
    if (message.group_id !== 0) {
      writer.uint32(24).uint64(message.group_id);
    }
    if (message.apply_msg !== "") {
      writer.uint32(34).string(message.apply_msg);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.handler_id !== 0) {
      writer.uint32(48).uint64(message.handler_id);
    }
    if (message.request_time !== 0) {
      writer.uint32(56).int64(message.request_time);
    }
    if (message.handle_time !== 0) {
      writer.uint32(64).int64(message.handle_time);
    }
    if (message.reject_reason !== "") {
      writer.uint32(74).string(message.reject_reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sender_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.apply_msg = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.handler_id = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.request_time = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.handle_time = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.reject_reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      sender_id: isSet(object.senderId)
        ? globalThis.Number(object.senderId)
        : isSet(object.sender_id)
        ? globalThis.Number(object.sender_id)
        : 0,
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      apply_msg: isSet(object.applyMsg)
        ? globalThis.String(object.applyMsg)
        : isSet(object.apply_msg)
        ? globalThis.String(object.apply_msg)
        : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      handler_id: isSet(object.handlerId)
        ? globalThis.Number(object.handlerId)
        : isSet(object.handler_id)
        ? globalThis.Number(object.handler_id)
        : 0,
      request_time: isSet(object.requestTime)
        ? globalThis.Number(object.requestTime)
        : isSet(object.request_time)
        ? globalThis.Number(object.request_time)
        : 0,
      handle_time: isSet(object.handleTime)
        ? globalThis.Number(object.handleTime)
        : isSet(object.handle_time)
        ? globalThis.Number(object.handle_time)
        : 0,
      reject_reason: isSet(object.rejectReason)
        ? globalThis.String(object.rejectReason)
        : isSet(object.reject_reason)
        ? globalThis.String(object.reject_reason)
        : "",
    };
  },

  toJSON(message: GroupRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.sender_id !== 0) {
      obj.senderId = Math.round(message.sender_id);
    }
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.apply_msg !== "") {
      obj.applyMsg = message.apply_msg;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.handler_id !== 0) {
      obj.handlerId = Math.round(message.handler_id);
    }
    if (message.request_time !== 0) {
      obj.requestTime = Math.round(message.request_time);
    }
    if (message.handle_time !== 0) {
      obj.handleTime = Math.round(message.handle_time);
    }
    if (message.reject_reason !== "") {
      obj.rejectReason = message.reject_reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupRequest>, I>>(base?: I): GroupRequest {
    return GroupRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupRequest>, I>>(object: I): GroupRequest {
    const message = createBaseGroupRequest();
    message.id = object.id ?? 0;
    message.sender_id = object.sender_id ?? 0;
    message.group_id = object.group_id ?? 0;
    message.apply_msg = object.apply_msg ?? "";
    message.status = object.status ?? 0;
    message.handler_id = object.handler_id ?? 0;
    message.request_time = object.request_time ?? 0;
    message.handle_time = object.handle_time ?? 0;
    message.reject_reason = object.reject_reason ?? "";
    return message;
  },
};

function createBaseCreateGroupReq(): CreateGroupReq {
  return { name: "", avatar: "", member_ids: [] };
}

export const CreateGroupReq: MessageFns<CreateGroupReq> = {
  encode(message: CreateGroupReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.avatar !== "") {
      writer.uint32(18).string(message.avatar);
    }
    writer.uint32(26).fork();
    for (const v of message.member_ids) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateGroupReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateGroupReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.member_ids.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.member_ids.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateGroupReq {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      member_ids: globalThis.Array.isArray(object?.memberIds)
        ? object.memberIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.member_ids)
        ? object.member_ids.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: CreateGroupReq): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.member_ids?.length) {
      obj.memberIds = message.member_ids.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateGroupReq>, I>>(base?: I): CreateGroupReq {
    return CreateGroupReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateGroupReq>, I>>(object: I): CreateGroupReq {
    const message = createBaseCreateGroupReq();
    message.name = object.name ?? "";
    message.avatar = object.avatar ?? "";
    message.member_ids = object.member_ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseCreateGroupResp(): CreateGroupResp {
  return { data: undefined };
}

export const CreateGroupResp: MessageFns<CreateGroupResp> = {
  encode(message: CreateGroupResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      Group.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateGroupResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateGroupResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Group.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateGroupResp {
    return { data: isSet(object.data) ? Group.fromJSON(object.data) : undefined };
  },

  toJSON(message: CreateGroupResp): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = Group.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateGroupResp>, I>>(base?: I): CreateGroupResp {
    return CreateGroupResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateGroupResp>, I>>(object: I): CreateGroupResp {
    const message = createBaseCreateGroupResp();
    message.data = (object.data !== undefined && object.data !== null) ? Group.fromPartial(object.data) : undefined;
    return message;
  },
};

function createBaseGetGroupReq(): GetGroupReq {
  return { group_ids: [], name_keyword: "", limit: 0, offset: 0 };
}

export const GetGroupReq: MessageFns<GetGroupReq> = {
  encode(message: GetGroupReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.group_ids) {
      writer.uint64(v);
    }
    writer.join();
    if (message.name_keyword !== "") {
      writer.uint32(18).string(message.name_keyword);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(32).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGroupReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGroupReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.group_ids.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.group_ids.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name_keyword = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGroupReq {
    return {
      group_ids: globalThis.Array.isArray(object?.groupIds)
        ? object.groupIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.group_ids)
        ? object.group_ids.map((e: any) => globalThis.Number(e))
        : [],
      name_keyword: isSet(object.nameKeyword)
        ? globalThis.String(object.nameKeyword)
        : isSet(object.name_keyword)
        ? globalThis.String(object.name_keyword)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: GetGroupReq): unknown {
    const obj: any = {};
    if (message.group_ids?.length) {
      obj.groupIds = message.group_ids.map((e) => Math.round(e));
    }
    if (message.name_keyword !== "") {
      obj.nameKeyword = message.name_keyword;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGroupReq>, I>>(base?: I): GetGroupReq {
    return GetGroupReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGroupReq>, I>>(object: I): GetGroupReq {
    const message = createBaseGetGroupReq();
    message.group_ids = object.group_ids?.map((e) => e) || [];
    message.name_keyword = object.name_keyword ?? "";
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseGetGroupMembersReq(): GetGroupMembersReq {
  return { group_id: 0 };
}

export const GetGroupMembersReq: MessageFns<GetGroupMembersReq> = {
  encode(message: GetGroupMembersReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGroupMembersReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGroupMembersReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGroupMembersReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
    };
  },

  toJSON(message: GetGroupMembersReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGroupMembersReq>, I>>(base?: I): GetGroupMembersReq {
    return GetGroupMembersReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGroupMembersReq>, I>>(object: I): GetGroupMembersReq {
    const message = createBaseGetGroupMembersReq();
    message.group_id = object.group_id ?? 0;
    return message;
  },
};

function createBaseGetGroupMembersResp(): GetGroupMembersResp {
  return { data: [] };
}

export const GetGroupMembersResp: MessageFns<GetGroupMembersResp> = {
  encode(message: GetGroupMembersResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      GroupMember.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGroupMembersResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGroupMembersResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(GroupMember.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGroupMembersResp {
    return { data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => GroupMember.fromJSON(e)) : [] };
  },

  toJSON(message: GetGroupMembersResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => GroupMember.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGroupMembersResp>, I>>(base?: I): GetGroupMembersResp {
    return GetGroupMembersResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGroupMembersResp>, I>>(object: I): GetGroupMembersResp {
    const message = createBaseGetGroupMembersResp();
    message.data = object.data?.map((e) => GroupMember.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetGroupResp(): GetGroupResp {
  return { data: [], total: 0 };
}

export const GetGroupResp: MessageFns<GetGroupResp> = {
  encode(message: GetGroupResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      Group.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int64(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGroupResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGroupResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(Group.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGroupResp {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => Group.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: GetGroupResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => Group.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGroupResp>, I>>(base?: I): GetGroupResp {
    return GetGroupResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGroupResp>, I>>(object: I): GetGroupResp {
    const message = createBaseGetGroupResp();
    message.data = object.data?.map((e) => Group.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseUpdateGroupReq(): UpdateGroupReq {
  return { group_id: 0, name: "", avatar: "", notice: "", join_type: 0 };
}

export const UpdateGroupReq: MessageFns<UpdateGroupReq> = {
  encode(message: UpdateGroupReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.avatar !== "") {
      writer.uint32(26).string(message.avatar);
    }
    if (message.notice !== "") {
      writer.uint32(34).string(message.notice);
    }
    if (message.join_type !== 0) {
      writer.uint32(40).int32(message.join_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateGroupReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateGroupReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.join_type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateGroupReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
      join_type: isSet(object.joinType)
        ? globalThis.Number(object.joinType)
        : isSet(object.join_type)
        ? globalThis.Number(object.join_type)
        : 0,
    };
  },

  toJSON(message: UpdateGroupReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    if (message.join_type !== 0) {
      obj.joinType = Math.round(message.join_type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateGroupReq>, I>>(base?: I): UpdateGroupReq {
    return UpdateGroupReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateGroupReq>, I>>(object: I): UpdateGroupReq {
    const message = createBaseUpdateGroupReq();
    message.group_id = object.group_id ?? 0;
    message.name = object.name ?? "";
    message.avatar = object.avatar ?? "";
    message.notice = object.notice ?? "";
    message.join_type = object.join_type ?? 0;
    return message;
  },
};

function createBaseJoinGroupReq(): JoinGroupReq {
  return { group_id: 0, message: "" };
}

export const JoinGroupReq: MessageFns<JoinGroupReq> = {
  encode(message: JoinGroupReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinGroupReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinGroupReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinGroupReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: JoinGroupReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinGroupReq>, I>>(base?: I): JoinGroupReq {
    return JoinGroupReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinGroupReq>, I>>(object: I): JoinGroupReq {
    const message = createBaseJoinGroupReq();
    message.group_id = object.group_id ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseJoinGroupResp(): JoinGroupResp {
  return { data: undefined, member: undefined };
}

export const JoinGroupResp: MessageFns<JoinGroupResp> = {
  encode(message: JoinGroupResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      GroupRequest.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.member !== undefined) {
      GroupMember.encode(message.member, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinGroupResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinGroupResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = GroupRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.member = GroupMember.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinGroupResp {
    return {
      data: isSet(object.data) ? GroupRequest.fromJSON(object.data) : undefined,
      member: isSet(object.member) ? GroupMember.fromJSON(object.member) : undefined,
    };
  },

  toJSON(message: JoinGroupResp): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = GroupRequest.toJSON(message.data);
    }
    if (message.member !== undefined) {
      obj.member = GroupMember.toJSON(message.member);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinGroupResp>, I>>(base?: I): JoinGroupResp {
    return JoinGroupResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinGroupResp>, I>>(object: I): JoinGroupResp {
    const message = createBaseJoinGroupResp();
    message.data = (object.data !== undefined && object.data !== null)
      ? GroupRequest.fromPartial(object.data)
      : undefined;
    message.member = (object.member !== undefined && object.member !== null)
      ? GroupMember.fromPartial(object.member)
      : undefined;
    return message;
  },
};

function createBaseHandleGroupApplyReq(): HandleGroupApplyReq {
  return { apply_id: 0, result: 0, reject_reason: "" };
}

export const HandleGroupApplyReq: MessageFns<HandleGroupApplyReq> = {
  encode(message: HandleGroupApplyReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apply_id !== 0) {
      writer.uint32(8).int64(message.apply_id);
    }
    if (message.result !== 0) {
      writer.uint32(16).int32(message.result);
    }
    if (message.reject_reason !== "") {
      writer.uint32(26).string(message.reject_reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HandleGroupApplyReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHandleGroupApplyReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.apply_id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.result = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reject_reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HandleGroupApplyReq {
    return {
      apply_id: isSet(object.applyId)
        ? globalThis.Number(object.applyId)
        : isSet(object.apply_id)
        ? globalThis.Number(object.apply_id)
        : 0,
      result: isSet(object.result) ? globalThis.Number(object.result) : 0,
      reject_reason: isSet(object.rejectReason)
        ? globalThis.String(object.rejectReason)
        : isSet(object.reject_reason)
        ? globalThis.String(object.reject_reason)
        : "",
    };
  },

  toJSON(message: HandleGroupApplyReq): unknown {
    const obj: any = {};
    if (message.apply_id !== 0) {
      obj.applyId = Math.round(message.apply_id);
    }
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    if (message.reject_reason !== "") {
      obj.rejectReason = message.reject_reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandleGroupApplyReq>, I>>(base?: I): HandleGroupApplyReq {
    return HandleGroupApplyReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandleGroupApplyReq>, I>>(object: I): HandleGroupApplyReq {
    const message = createBaseHandleGroupApplyReq();
    message.apply_id = object.apply_id ?? 0;
    message.result = object.result ?? 0;
    message.reject_reason = object.reject_reason ?? "";
    return message;
  },
};

function createBaseHandleGroupApplyResp(): HandleGroupApplyResp {
  return { data: undefined };
}

export const HandleGroupApplyResp: MessageFns<HandleGroupApplyResp> = {
  encode(message: HandleGroupApplyResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      GroupRequest.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HandleGroupApplyResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHandleGroupApplyResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = GroupRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HandleGroupApplyResp {
    return { data: isSet(object.data) ? GroupRequest.fromJSON(object.data) : undefined };
  },

  toJSON(message: HandleGroupApplyResp): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = GroupRequest.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandleGroupApplyResp>, I>>(base?: I): HandleGroupApplyResp {
    return HandleGroupApplyResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandleGroupApplyResp>, I>>(object: I): HandleGroupApplyResp {
    const message = createBaseHandleGroupApplyResp();
    message.data = (object.data !== undefined && object.data !== null)
      ? GroupRequest.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseInviteMembersReq(): InviteMembersReq {
  return { group_id: 0, member_ids: [] };
}

export const InviteMembersReq: MessageFns<InviteMembersReq> = {
  encode(message: InviteMembersReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    writer.uint32(18).fork();
    for (const v of message.member_ids) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InviteMembersReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInviteMembersReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.member_ids.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.member_ids.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InviteMembersReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      member_ids: globalThis.Array.isArray(object?.memberIds)
        ? object.memberIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.member_ids)
        ? object.member_ids.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: InviteMembersReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.member_ids?.length) {
      obj.memberIds = message.member_ids.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InviteMembersReq>, I>>(base?: I): InviteMembersReq {
    return InviteMembersReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InviteMembersReq>, I>>(object: I): InviteMembersReq {
    const message = createBaseInviteMembersReq();
    message.group_id = object.group_id ?? 0;
    message.member_ids = object.member_ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseInviteMembersResp(): InviteMembersResp {
  return { success_count: 0, failed_ids: [] };
}

export const InviteMembersResp: MessageFns<InviteMembersResp> = {
  encode(message: InviteMembersResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success_count !== 0) {
      writer.uint32(8).int32(message.success_count);
    }
    writer.uint32(18).fork();
    for (const v of message.failed_ids) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InviteMembersResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInviteMembersResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success_count = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.failed_ids.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.failed_ids.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InviteMembersResp {
    return {
      success_count: isSet(object.successCount)
        ? globalThis.Number(object.successCount)
        : isSet(object.success_count)
        ? globalThis.Number(object.success_count)
        : 0,
      failed_ids: globalThis.Array.isArray(object?.failedIds)
        ? object.failedIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.failed_ids)
        ? object.failed_ids.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: InviteMembersResp): unknown {
    const obj: any = {};
    if (message.success_count !== 0) {
      obj.successCount = Math.round(message.success_count);
    }
    if (message.failed_ids?.length) {
      obj.failedIds = message.failed_ids.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InviteMembersResp>, I>>(base?: I): InviteMembersResp {
    return InviteMembersResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InviteMembersResp>, I>>(object: I): InviteMembersResp {
    const message = createBaseInviteMembersResp();
    message.success_count = object.success_count ?? 0;
    message.failed_ids = object.failed_ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseRemoveMemberReq(): RemoveMemberReq {
  return { group_id: 0, user_id: 0, operator_id: 0 };
}

export const RemoveMemberReq: MessageFns<RemoveMemberReq> = {
  encode(message: RemoveMemberReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.user_id !== 0) {
      writer.uint32(16).uint64(message.user_id);
    }
    if (message.operator_id !== 0) {
      writer.uint32(24).uint64(message.operator_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveMemberReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveMemberReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.operator_id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveMemberReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      operator_id: isSet(object.operatorId)
        ? globalThis.Number(object.operatorId)
        : isSet(object.operator_id)
        ? globalThis.Number(object.operator_id)
        : 0,
    };
  },

  toJSON(message: RemoveMemberReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.operator_id !== 0) {
      obj.operatorId = Math.round(message.operator_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveMemberReq>, I>>(base?: I): RemoveMemberReq {
    return RemoveMemberReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveMemberReq>, I>>(object: I): RemoveMemberReq {
    const message = createBaseRemoveMemberReq();
    message.group_id = object.group_id ?? 0;
    message.user_id = object.user_id ?? 0;
    message.operator_id = object.operator_id ?? 0;
    return message;
  },
};

function createBaseLeaveGroupReq(): LeaveGroupReq {
  return { group_id: 0 };
}

export const LeaveGroupReq: MessageFns<LeaveGroupReq> = {
  encode(message: LeaveGroupReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaveGroupReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaveGroupReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LeaveGroupReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
    };
  },

  toJSON(message: LeaveGroupReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LeaveGroupReq>, I>>(base?: I): LeaveGroupReq {
    return LeaveGroupReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeaveGroupReq>, I>>(object: I): LeaveGroupReq {
    const message = createBaseLeaveGroupReq();
    message.group_id = object.group_id ?? 0;
    return message;
  },
};

function createBaseDismissGroupReq(): DismissGroupReq {
  return { group_id: 0 };
}

export const DismissGroupReq: MessageFns<DismissGroupReq> = {
  encode(message: DismissGroupReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DismissGroupReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDismissGroupReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DismissGroupReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
    };
  },

  toJSON(message: DismissGroupReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DismissGroupReq>, I>>(base?: I): DismissGroupReq {
    return DismissGroupReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DismissGroupReq>, I>>(object: I): DismissGroupReq {
    const message = createBaseDismissGroupReq();
    message.group_id = object.group_id ?? 0;
    return message;
  },
};

function createBaseSetMemberRoleReq(): SetMemberRoleReq {
  return { group_id: 0, user_id: 0, role: 0, operator_id: 0 };
}

export const SetMemberRoleReq: MessageFns<SetMemberRoleReq> = {
  encode(message: SetMemberRoleReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.user_id !== 0) {
      writer.uint32(16).uint64(message.user_id);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    if (message.operator_id !== 0) {
      writer.uint32(32).uint64(message.operator_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMemberRoleReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetMemberRoleReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.operator_id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetMemberRoleReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      role: isSet(object.role) ? globalThis.Number(object.role) : 0,
      operator_id: isSet(object.operatorId)
        ? globalThis.Number(object.operatorId)
        : isSet(object.operator_id)
        ? globalThis.Number(object.operator_id)
        : 0,
    };
  },

  toJSON(message: SetMemberRoleReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.role !== 0) {
      obj.role = Math.round(message.role);
    }
    if (message.operator_id !== 0) {
      obj.operatorId = Math.round(message.operator_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMemberRoleReq>, I>>(base?: I): SetMemberRoleReq {
    return SetMemberRoleReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMemberRoleReq>, I>>(object: I): SetMemberRoleReq {
    const message = createBaseSetMemberRoleReq();
    message.group_id = object.group_id ?? 0;
    message.user_id = object.user_id ?? 0;
    message.role = object.role ?? 0;
    message.operator_id = object.operator_id ?? 0;
    return message;
  },
};

function createBaseSetMemberNicknameReq(): SetMemberNicknameReq {
  return { group_id: 0, nickname: "" };
}

export const SetMemberNicknameReq: MessageFns<SetMemberNicknameReq> = {
  encode(message: SetMemberNicknameReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.nickname !== "") {
      writer.uint32(18).string(message.nickname);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMemberNicknameReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetMemberNicknameReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetMemberNicknameReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
    };
  },

  toJSON(message: SetMemberNicknameReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMemberNicknameReq>, I>>(base?: I): SetMemberNicknameReq {
    return SetMemberNicknameReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMemberNicknameReq>, I>>(object: I): SetMemberNicknameReq {
    const message = createBaseSetMemberNicknameReq();
    message.group_id = object.group_id ?? 0;
    message.nickname = object.nickname ?? "";
    return message;
  },
};

function createBaseMuteMemberReq(): MuteMemberReq {
  return { group_id: 0, user_id: 0, mute_until: 0 };
}

export const MuteMemberReq: MessageFns<MuteMemberReq> = {
  encode(message: MuteMemberReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.user_id !== 0) {
      writer.uint32(16).uint64(message.user_id);
    }
    if (message.mute_until !== 0) {
      writer.uint32(24).int64(message.mute_until);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MuteMemberReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMuteMemberReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mute_until = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MuteMemberReq {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      mute_until: isSet(object.muteUntil)
        ? globalThis.Number(object.muteUntil)
        : isSet(object.mute_until)
        ? globalThis.Number(object.mute_until)
        : 0,
    };
  },

  toJSON(message: MuteMemberReq): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.mute_until !== 0) {
      obj.muteUntil = Math.round(message.mute_until);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MuteMemberReq>, I>>(base?: I): MuteMemberReq {
    return MuteMemberReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MuteMemberReq>, I>>(object: I): MuteMemberReq {
    const message = createBaseMuteMemberReq();
    message.group_id = object.group_id ?? 0;
    message.user_id = object.user_id ?? 0;
    message.mute_until = object.mute_until ?? 0;
    return message;
  },
};

function createBaseGetUserGroupsReq(): GetUserGroupsReq {
  return {};
}

export const GetUserGroupsReq: MessageFns<GetUserGroupsReq> = {
  encode(_: GetUserGroupsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserGroupsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserGroupsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetUserGroupsReq {
    return {};
  },

  toJSON(_: GetUserGroupsReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserGroupsReq>, I>>(base?: I): GetUserGroupsReq {
    return GetUserGroupsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserGroupsReq>, I>>(_: I): GetUserGroupsReq {
    const message = createBaseGetUserGroupsReq();
    return message;
  },
};

function createBaseGetUserGroupsResp(): GetUserGroupsResp {
  return { data: [] };
}

export const GetUserGroupsResp: MessageFns<GetUserGroupsResp> = {
  encode(message: GetUserGroupsResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.data) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserGroupsResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserGroupsResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.data.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.data.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserGroupsResp {
    return { data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: GetUserGroupsResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserGroupsResp>, I>>(base?: I): GetUserGroupsResp {
    return GetUserGroupsResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserGroupsResp>, I>>(object: I): GetUserGroupsResp {
    const message = createBaseGetUserGroupsResp();
    message.data = object.data?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetPendingAppliesReq(): GetPendingAppliesReq {
  return {};
}

export const GetPendingAppliesReq: MessageFns<GetPendingAppliesReq> = {
  encode(_: GetPendingAppliesReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPendingAppliesReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPendingAppliesReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetPendingAppliesReq {
    return {};
  },

  toJSON(_: GetPendingAppliesReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPendingAppliesReq>, I>>(base?: I): GetPendingAppliesReq {
    return GetPendingAppliesReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPendingAppliesReq>, I>>(_: I): GetPendingAppliesReq {
    const message = createBaseGetPendingAppliesReq();
    return message;
  },
};

function createBaseGetPendingAppliesResp(): GetPendingAppliesResp {
  return { data: [] };
}

export const GetPendingAppliesResp: MessageFns<GetPendingAppliesResp> = {
  encode(message: GetPendingAppliesResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      GroupRequest.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPendingAppliesResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPendingAppliesResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(GroupRequest.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPendingAppliesResp {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => GroupRequest.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetPendingAppliesResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => GroupRequest.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPendingAppliesResp>, I>>(base?: I): GetPendingAppliesResp {
    return GetPendingAppliesResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPendingAppliesResp>, I>>(object: I): GetPendingAppliesResp {
    const message = createBaseGetPendingAppliesResp();
    message.data = object.data?.map((e) => GroupRequest.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
