/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    BlankPage: typeof import('./src/components/BlankPage.vue')['default']
    BoxReveal: typeof import('./src/components/BoxReveal.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CusButton: typeof import('./src/components/CusButton.vue')['default']
    CusCheckBox: typeof import('./src/components/CusCheckBox.vue')['default']
    CusDialog: typeof import('./src/components/CusDialog/CusDialog.vue')['default']
    CusDropdown: typeof import('./src/components/CusDropdown.vue')['default']
    CusInput: typeof import('./src/components/CusInput.vue')['default']
    CusInputDialog: typeof import('./src/components/CusInputDialog/CusInputDialog.vue')['default']
    CusInputHint: typeof import('./src/components/CusInputHint.vue')['default']
    CusModal: typeof import('./src/components/CusModal.vue')['default']
    CusSpinner: typeof import('./src/components/CusSpinner.vue')['default']
    CusSwitch: typeof import('./src/components/CusSwitch.vue')['default']
    FilterColumn: typeof import('./src/components/FilterColumn.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading/GlobalLoading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ModalBackground: typeof import('./src/components/ModalBackground/ModalBackground.vue')['default']
    PasswordStrength: typeof import('./src/components/PasswordStrength.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    UserSelectorModal: typeof import('./src/components/UserSelectorModal.vue')['default']
  }
}
