$ErrorActionPreference = "Stop"

$typesDir = Join-Path $PSScriptRoot "share\types"
$apisDir = Join-Path $typesDir "apis"

# 1. Generate Proto types using ts-proto
Write-Host "Searching for .proto files in $typesDir..."
$protoFiles = Get-ChildItem -Path $typesDir -Recurse -Filter *.proto

if ($protoFiles) {
    Write-Host "Found $($protoFiles.Count) proto files."
    
    $files = $protoFiles.FullName
    $pluginPath = Join-Path $PSScriptRoot "node_modules\.bin\protoc-gen-ts_proto.cmd"
    
    if (-not (Test-Path $pluginPath)) {
        Write-Error "ts-proto plugin not found at $pluginPath. Please run 'npm install ts-proto --save-dev'"
        exit 1
    }

    # ts-proto options
    # forceLong=number: Generate number instead of string/Long for int64
    # esModuleInterop=true: Fix import issues
    # outputServices=false: We only want types for now
    # outputClientImpl=false: We only want types
    # snakeToCamel=false: Keep snake_case in interfaces (critical for JSON backend compatibility)
    
    $tsProtoOpt = "forceLong=number,esModuleInterop=true,outputServices=false,outputClientImpl=false,useProtoFieldName=true,snakeToCamel=false"
    
    $protocArgs = @(
        "-I=$typesDir",
        "--plugin=protoc-gen-ts_proto=$pluginPath",
        "--ts_proto_out=$typesDir",
        "--ts_proto_opt=$tsProtoOpt"
    ) + $files
    
    Write-Host "Protoc Args: $($protocArgs -join ' ')"
    
    try {
        & protoc $protocArgs
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Protoc failed with exit code $LASTEXITCODE"
        } else {
             Write-Host "Proto generation successful."
        }
    } catch {
        Write-Error "Error executing protoc: $_"
    }
} else {
    Write-Warning "No .proto files found."
}

# 2. Generate index.ts for apis
# ts-proto generates [filename].ts in the same directory as [filename].proto
if (Test-Path $apisDir) {
    Write-Host "Generating index.ts for APIs in $apisDir..."
    $apiIndexFile = Join-Path $apisDir "index.ts"
    $sb = new-object System.Text.StringBuilder

    $sb.AppendLine("// Auto-generated by gen-proto.ps1") | Out-Null
    $sb.AppendLine("// Do not edit directly") | Out-Null
    $sb.AppendLine("") | Out-Null

    # We want to export based on the subdirectory structure
    # Get all subdirectories in APIs
    $SubDirs = Get-ChildItem -Path $apisDir -Directory
    
    foreach ($Dir in $SubDirs) {
        $DirName = $Dir.Name
        # Find the generated .ts file. It should match the directory name usually, or the proto filename.
        # Let's find .ts files that are NOT index.ts and NOT _pb.ts (old)
        
        # Actually, let's look for the .proto file to know the expected .ts file name
        $ProtoFiles = Get-ChildItem -Path $Dir.FullName -Filter *.proto
        
        foreach ($Proto in $ProtoFiles) {
             $BaseName = $Proto.BaseName
             # Generated file is BaseName.ts
             $GeneratedFile = Join-Path $Dir.FullName "$BaseName.ts"
             
             if (Test-Path $GeneratedFile) {
                 # Export generic namespace
                 # export * as auth from './auth/auth';
                 $sb.AppendLine("export * as $BaseName from './$DirName/$BaseName';") | Out-Null
             }
        }
    }

    $sb.ToString() | Out-File -FilePath $apiIndexFile -Encoding utf8
    Write-Host "Generated index.ts at $apiIndexFile"
} else {
    Write-Warning "APIs directory not found at $apisDir"
}

Write-Host "Done."
