// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.31.1
// source: proto/user/user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "user";

export enum JoinType {
  JOIN_TYPE_UNSPECIFIED = 0,
  /** JOIN_TYPE_AFTER_APPROVAL - 同意后加入 */
  JOIN_TYPE_AFTER_APPROVAL = 1,
  /** JOIN_TYPE_DIRECT - 直接加入 */
  JOIN_TYPE_DIRECT = 2,
  UNRECOGNIZED = -1,
}

export function joinTypeFromJSON(object: any): JoinType {
  switch (object) {
    case 0:
    case "JOIN_TYPE_UNSPECIFIED":
      return JoinType.JOIN_TYPE_UNSPECIFIED;
    case 1:
    case "JOIN_TYPE_AFTER_APPROVAL":
      return JoinType.JOIN_TYPE_AFTER_APPROVAL;
    case 2:
    case "JOIN_TYPE_DIRECT":
      return JoinType.JOIN_TYPE_DIRECT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JoinType.UNRECOGNIZED;
  }
}

export function joinTypeToJSON(object: JoinType): string {
  switch (object) {
    case JoinType.JOIN_TYPE_UNSPECIFIED:
      return "JOIN_TYPE_UNSPECIFIED";
    case JoinType.JOIN_TYPE_AFTER_APPROVAL:
      return "JOIN_TYPE_AFTER_APPROVAL";
    case JoinType.JOIN_TYPE_DIRECT:
      return "JOIN_TYPE_DIRECT";
    case JoinType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Gender {
  GENDER_UNSPECIFIED = 0,
  GENDER_MALE = 1,
  GENDER_FEMALE = 2,
  /** GENDER_UNKNOWN - TS: Unknown=3 */
  GENDER_UNKNOWN = 3,
  UNRECOGNIZED = -1,
}

export function genderFromJSON(object: any): Gender {
  switch (object) {
    case 0:
    case "GENDER_UNSPECIFIED":
      return Gender.GENDER_UNSPECIFIED;
    case 1:
    case "GENDER_MALE":
      return Gender.GENDER_MALE;
    case 2:
    case "GENDER_FEMALE":
      return Gender.GENDER_FEMALE;
    case 3:
    case "GENDER_UNKNOWN":
      return Gender.GENDER_UNKNOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Gender.UNRECOGNIZED;
  }
}

export function genderToJSON(object: Gender): string {
  switch (object) {
    case Gender.GENDER_UNSPECIFIED:
      return "GENDER_UNSPECIFIED";
    case Gender.GENDER_MALE:
      return "GENDER_MALE";
    case Gender.GENDER_FEMALE:
      return "GENDER_FEMALE";
    case Gender.GENDER_UNKNOWN:
      return "GENDER_UNKNOWN";
    case Gender.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum UserStatus {
  /** USER_STATUS_DISABLED - 禁用 */
  USER_STATUS_DISABLED = 0,
  /** USER_STATUS_NORMAL - 正常 */
  USER_STATUS_NORMAL = 1,
  UNRECOGNIZED = -1,
}

export function userStatusFromJSON(object: any): UserStatus {
  switch (object) {
    case 0:
    case "USER_STATUS_DISABLED":
      return UserStatus.USER_STATUS_DISABLED;
    case 1:
    case "USER_STATUS_NORMAL":
      return UserStatus.USER_STATUS_NORMAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserStatus.UNRECOGNIZED;
  }
}

export function userStatusToJSON(object: UserStatus): string {
  switch (object) {
    case UserStatus.USER_STATUS_DISABLED:
      return "USER_STATUS_DISABLED";
    case UserStatus.USER_STATUS_NORMAL:
      return "USER_STATUS_NORMAL";
    case UserStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OnlineStatus {
  /** ONLINE_STATUS_OFFLINE - 离线 */
  ONLINE_STATUS_OFFLINE = 0,
  /** ONLINE_STATUS_ONLINE - 在线 */
  ONLINE_STATUS_ONLINE = 1,
  /** ONLINE_STATUS_AWAY - 离开 */
  ONLINE_STATUS_AWAY = 2,
  /** ONLINE_STATUS_BUSY - 忙碌 */
  ONLINE_STATUS_BUSY = 3,
  /** ONLINE_STATUS_INVISIBLE - 隐身 */
  ONLINE_STATUS_INVISIBLE = 4,
  UNRECOGNIZED = -1,
}

export function onlineStatusFromJSON(object: any): OnlineStatus {
  switch (object) {
    case 0:
    case "ONLINE_STATUS_OFFLINE":
      return OnlineStatus.ONLINE_STATUS_OFFLINE;
    case 1:
    case "ONLINE_STATUS_ONLINE":
      return OnlineStatus.ONLINE_STATUS_ONLINE;
    case 2:
    case "ONLINE_STATUS_AWAY":
      return OnlineStatus.ONLINE_STATUS_AWAY;
    case 3:
    case "ONLINE_STATUS_BUSY":
      return OnlineStatus.ONLINE_STATUS_BUSY;
    case 4:
    case "ONLINE_STATUS_INVISIBLE":
      return OnlineStatus.ONLINE_STATUS_INVISIBLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OnlineStatus.UNRECOGNIZED;
  }
}

export function onlineStatusToJSON(object: OnlineStatus): string {
  switch (object) {
    case OnlineStatus.ONLINE_STATUS_OFFLINE:
      return "ONLINE_STATUS_OFFLINE";
    case OnlineStatus.ONLINE_STATUS_ONLINE:
      return "ONLINE_STATUS_ONLINE";
    case OnlineStatus.ONLINE_STATUS_AWAY:
      return "ONLINE_STATUS_AWAY";
    case OnlineStatus.ONLINE_STATUS_BUSY:
      return "ONLINE_STATUS_BUSY";
    case OnlineStatus.ONLINE_STATUS_INVISIBLE:
      return "ONLINE_STATUS_INVISIBLE";
    case OnlineStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface UserInfo {
  /** 用户ID */
  user_id: number;
  /** 用户名 */
  user_name: string;
  /** 头像 */
  avatar: string;
  /** 性别 */
  gender: Gender;
  /** 手机号 */
  phone: string;
  /** 加入类型 */
  join_type: JoinType;
  /** 状态 */
  status: UserStatus;
  /** 签名 */
  personal_signature: string;
  /** 创建时间 */
  create_time: number;
  /** 更新时间 */
  update_time: number;
}

/** 用户在线状态 */
export interface UserOnlineStatus {
  /** 用户ID */
  user_id: number;
  /** 在线状态 */
  status: OnlineStatus;
  /** 最后活跃时间 */
  last_active_time: number;
}

/** 正在输入 */
export interface TypingStatus {
  /** 用户ID */
  user_id: number;
  /** 会话ID */
  conversation_id: string;
  /** 是否正在输入 */
  is_typing: boolean;
  /** 时间戳 */
  timestamp: number;
}

export interface UserKickoff {
  /** 用户ID */
  user_id: number;
  /** 踢出原因 */
  reason: string;
  /** 时间戳 */
  timestamp: number;
}

function createBaseUserInfo(): UserInfo {
  return {
    user_id: 0,
    user_name: "",
    avatar: "",
    gender: 0,
    phone: "",
    join_type: 0,
    status: 0,
    personal_signature: "",
    create_time: 0,
    update_time: 0,
  };
}

export const UserInfo: MessageFns<UserInfo> = {
  encode(message: UserInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.user_name !== "") {
      writer.uint32(18).string(message.user_name);
    }
    if (message.avatar !== "") {
      writer.uint32(26).string(message.avatar);
    }
    if (message.gender !== 0) {
      writer.uint32(32).int32(message.gender);
    }
    if (message.phone !== "") {
      writer.uint32(42).string(message.phone);
    }
    if (message.join_type !== 0) {
      writer.uint32(48).int32(message.join_type);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.personal_signature !== "") {
      writer.uint32(66).string(message.personal_signature);
    }
    if (message.create_time !== 0) {
      writer.uint32(72).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(80).int64(message.update_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.gender = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.join_type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.personal_signature = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserInfo {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      user_name: isSet(object.userName)
        ? globalThis.String(object.userName)
        : isSet(object.user_name)
        ? globalThis.String(object.user_name)
        : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      gender: isSet(object.gender) ? genderFromJSON(object.gender) : 0,
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      join_type: isSet(object.joinType)
        ? joinTypeFromJSON(object.joinType)
        : isSet(object.join_type)
        ? joinTypeFromJSON(object.join_type)
        : 0,
      status: isSet(object.status) ? userStatusFromJSON(object.status) : 0,
      personal_signature: isSet(object.personalSignature)
        ? globalThis.String(object.personalSignature)
        : isSet(object.personal_signature)
        ? globalThis.String(object.personal_signature)
        : "",
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
    };
  },

  toJSON(message: UserInfo): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.user_name !== "") {
      obj.userName = message.user_name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.gender !== 0) {
      obj.gender = genderToJSON(message.gender);
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.join_type !== 0) {
      obj.joinType = joinTypeToJSON(message.join_type);
    }
    if (message.status !== 0) {
      obj.status = userStatusToJSON(message.status);
    }
    if (message.personal_signature !== "") {
      obj.personalSignature = message.personal_signature;
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserInfo>, I>>(base?: I): UserInfo {
    return UserInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserInfo>, I>>(object: I): UserInfo {
    const message = createBaseUserInfo();
    message.user_id = object.user_id ?? 0;
    message.user_name = object.user_name ?? "";
    message.avatar = object.avatar ?? "";
    message.gender = object.gender ?? 0;
    message.phone = object.phone ?? "";
    message.join_type = object.join_type ?? 0;
    message.status = object.status ?? 0;
    message.personal_signature = object.personal_signature ?? "";
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    return message;
  },
};

function createBaseUserOnlineStatus(): UserOnlineStatus {
  return { user_id: 0, status: 0, last_active_time: 0 };
}

export const UserOnlineStatus: MessageFns<UserOnlineStatus> = {
  encode(message: UserOnlineStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.last_active_time !== 0) {
      writer.uint32(24).int64(message.last_active_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserOnlineStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserOnlineStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.last_active_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserOnlineStatus {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      status: isSet(object.status) ? onlineStatusFromJSON(object.status) : 0,
      last_active_time: isSet(object.lastActiveTime)
        ? globalThis.Number(object.lastActiveTime)
        : isSet(object.last_active_time)
        ? globalThis.Number(object.last_active_time)
        : 0,
    };
  },

  toJSON(message: UserOnlineStatus): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.status !== 0) {
      obj.status = onlineStatusToJSON(message.status);
    }
    if (message.last_active_time !== 0) {
      obj.lastActiveTime = Math.round(message.last_active_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserOnlineStatus>, I>>(base?: I): UserOnlineStatus {
    return UserOnlineStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserOnlineStatus>, I>>(object: I): UserOnlineStatus {
    const message = createBaseUserOnlineStatus();
    message.user_id = object.user_id ?? 0;
    message.status = object.status ?? 0;
    message.last_active_time = object.last_active_time ?? 0;
    return message;
  },
};

function createBaseTypingStatus(): TypingStatus {
  return { user_id: 0, conversation_id: "", is_typing: false, timestamp: 0 };
}

export const TypingStatus: MessageFns<TypingStatus> = {
  encode(message: TypingStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.conversation_id !== "") {
      writer.uint32(18).string(message.conversation_id);
    }
    if (message.is_typing !== false) {
      writer.uint32(24).bool(message.is_typing);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TypingStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTypingStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_typing = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TypingStatus {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      is_typing: isSet(object.isTyping)
        ? globalThis.Boolean(object.isTyping)
        : isSet(object.is_typing)
        ? globalThis.Boolean(object.is_typing)
        : false,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: TypingStatus): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.is_typing !== false) {
      obj.isTyping = message.is_typing;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TypingStatus>, I>>(base?: I): TypingStatus {
    return TypingStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TypingStatus>, I>>(object: I): TypingStatus {
    const message = createBaseTypingStatus();
    message.user_id = object.user_id ?? 0;
    message.conversation_id = object.conversation_id ?? "";
    message.is_typing = object.is_typing ?? false;
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseUserKickoff(): UserKickoff {
  return { user_id: 0, reason: "", timestamp: 0 };
}

export const UserKickoff: MessageFns<UserKickoff> = {
  encode(message: UserKickoff, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserKickoff {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserKickoff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserKickoff {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: UserKickoff): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserKickoff>, I>>(base?: I): UserKickoff {
    return UserKickoff.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserKickoff>, I>>(object: I): UserKickoff {
    const message = createBaseUserKickoff();
    message.user_id = object.user_id ?? 0;
    message.reason = object.reason ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
