// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.31.1
// source: apis/user/user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types.user";

/** UserInfo */
export interface UserInfo {
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"user_name" */
  user_name: string;
  /** @gotags: json:"avatar" */
  avatar: string;
  /** @gotags: json:"gender" */
  gender: number;
  /** @gotags: json:"phone" */
  phone: string;
  /** @gotags: json:"join_type" */
  join_type: number;
  /** @gotags: json:"personal_signature" */
  personal_signature: string;
  /** @gotags: json:"status" */
  status: number;
  /** @gotags: json:"create_time" */
  create_time: number;
  /** @gotags: json:"update_time" */
  update_time: number;
}

/** Friend */
export interface Friend {
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"friend_id" */
  friend_id: number;
  /** @gotags: json:"remark" */
  remark: string;
  /** @gotags: json:"source" */
  source: number;
  /** @gotags: json:"blocked" */
  blocked: boolean;
  /** @gotags: json:"starred" */
  starred: boolean;
  /** @gotags: json:"create_time" */
  create_time: number;
  /** @gotags: json:"extra" */
  extra: string;
}

/** FriendRequest */
export interface FriendRequest {
  /** @gotags: json:"id" */
  id: number;
  /** @gotags: json:"from_user_id" */
  from_user_id: number;
  /** @gotags: json:"to_user_id" */
  to_user_id: number;
  /** @gotags: json:"apply_msg" */
  apply_msg: string;
  /** @gotags: json:"status" */
  status: number;
  /** @gotags: json:"source" */
  source: number;
  /** @gotags: json:"request_time" */
  request_time: number;
  /** @gotags: json:"handle_time" */
  handle_time: number;
  /** @gotags: json:"reject_reason" */
  reject_reason: string;
}

/** GetUserInfoReq */
export interface GetUserInfoReq {
  /** @gotags: form:"ids,optional" json:"ids,optional" */
  ids: number[];
  /** @gotags: form:"phone,optional" json:"phone,optional" */
  phone: string;
  /** @gotags: form:"name,optional" json:"name,optional" */
  name: string;
  /** @gotags: form:"limit,optional,default=20" json:"limit,optional,default=20" */
  limit: number;
  /** @gotags: form:"offset,optional,default=0" json:"offset,optional,default=0" */
  offset: number;
}

/** GetUserInfoResp */
export interface GetUserInfoResp {
  data: UserInfo[];
}

/** UpdateInfoReq */
export interface UpdateInfoReq {
  /** @gotags: json:"user_name,optional" */
  user_name: string;
  /** @gotags: json:"gender,optional" */
  gender: number;
  /** @gotags: json:"avatar,optional" */
  avatar: string;
  /** @gotags: json:"join_type,optional" */
  join_type: number;
  /** @gotags: json:"personal_signature,optional" */
  personal_signature: string;
}

/** GetFriendsReq */
export interface GetFriendsReq {
}

/** GetFriendsResp */
export interface GetFriendsResp {
  data: Friend[];
}

/** CreateFriendReq */
export interface CreateFriendReq {
  /** @gotags: json:"friend_id" */
  friend_id: number;
  /** @gotags: json:"source,optional" */
  source: number;
  /** @gotags: json:"remark,optional" */
  remark: string;
}

/** UpdateFriendReq */
export interface UpdateFriendReq {
  /** @gotags: json:"friend_id" */
  friend_id: number;
  /** @gotags: json:"remark,optional" */
  remark: string;
  /** @gotags: json:"blocked,optional" */
  blocked: boolean;
  /** @gotags: json:"starred,optional" */
  starred: boolean;
}

/** DeleteFriendReq */
export interface DeleteFriendReq {
  /** @gotags: json:"friend_id" */
  friend_id: number;
}

/** NewFriendApplyReq */
export interface NewFriendApplyReq {
  /** @gotags: json:"to_user_id" */
  to_user_id: number;
  /** @gotags: json:"apply_msg,optional" */
  apply_msg: string;
  /** @gotags: json:"source,optional" */
  source: number;
}

/** NewFriendApplyResp */
export interface NewFriendApplyResp {
  data: FriendRequest | undefined;
}

/** HandleFriendApplyReq */
export interface HandleFriendApplyReq {
  /** @gotags: json:"request_id" */
  request_id: number;
  /** @gotags: json:"result" */
  result: number;
  /** @gotags: json:"reject_reason,optional" */
  reject_reason: string;
}

/** GetPendingFriendAppliesReq */
export interface GetPendingFriendAppliesReq {
}

/** GetPendingFriendAppliesResp */
export interface GetPendingFriendAppliesResp {
  data: FriendRequest[];
}

/** SearchFriendReq */
export interface SearchFriendReq {
  /** @gotags: form:"name,optional" json:"name,optional" */
  name: string;
  /** @gotags: form:"id,optional" json:"id,optional" */
  id: number;
  /** @gotags: form:"phone,optional" json:"phone,optional" */
  phone: string;
  /** @gotags: form:"limit,optional,default=30" json:"limit,optional,default=30" */
  limit: number;
  /** @gotags: form:"offset,optional,default=0" json:"offset,optional,default=0" */
  offset: number;
}

/** SearchFriendResp */
export interface SearchFriendResp {
  data: UserInfo[];
  total: number;
}

function createBaseUserInfo(): UserInfo {
  return {
    user_id: 0,
    user_name: "",
    avatar: "",
    gender: 0,
    phone: "",
    join_type: 0,
    personal_signature: "",
    status: 0,
    create_time: 0,
    update_time: 0,
  };
}

export const UserInfo: MessageFns<UserInfo> = {
  encode(message: UserInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.user_name !== "") {
      writer.uint32(18).string(message.user_name);
    }
    if (message.avatar !== "") {
      writer.uint32(26).string(message.avatar);
    }
    if (message.gender !== 0) {
      writer.uint32(32).int32(message.gender);
    }
    if (message.phone !== "") {
      writer.uint32(42).string(message.phone);
    }
    if (message.join_type !== 0) {
      writer.uint32(48).int32(message.join_type);
    }
    if (message.personal_signature !== "") {
      writer.uint32(58).string(message.personal_signature);
    }
    if (message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.create_time !== 0) {
      writer.uint32(72).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(80).int64(message.update_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.gender = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.join_type = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.personal_signature = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserInfo {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      user_name: isSet(object.userName)
        ? globalThis.String(object.userName)
        : isSet(object.user_name)
        ? globalThis.String(object.user_name)
        : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      gender: isSet(object.gender) ? globalThis.Number(object.gender) : 0,
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      join_type: isSet(object.joinType)
        ? globalThis.Number(object.joinType)
        : isSet(object.join_type)
        ? globalThis.Number(object.join_type)
        : 0,
      personal_signature: isSet(object.personalSignature)
        ? globalThis.String(object.personalSignature)
        : isSet(object.personal_signature)
        ? globalThis.String(object.personal_signature)
        : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
    };
  },

  toJSON(message: UserInfo): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.user_name !== "") {
      obj.userName = message.user_name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.gender !== 0) {
      obj.gender = Math.round(message.gender);
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.join_type !== 0) {
      obj.joinType = Math.round(message.join_type);
    }
    if (message.personal_signature !== "") {
      obj.personalSignature = message.personal_signature;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserInfo>, I>>(base?: I): UserInfo {
    return UserInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserInfo>, I>>(object: I): UserInfo {
    const message = createBaseUserInfo();
    message.user_id = object.user_id ?? 0;
    message.user_name = object.user_name ?? "";
    message.avatar = object.avatar ?? "";
    message.gender = object.gender ?? 0;
    message.phone = object.phone ?? "";
    message.join_type = object.join_type ?? 0;
    message.personal_signature = object.personal_signature ?? "";
    message.status = object.status ?? 0;
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    return message;
  },
};

function createBaseFriend(): Friend {
  return { user_id: 0, friend_id: 0, remark: "", source: 0, blocked: false, starred: false, create_time: 0, extra: "" };
}

export const Friend: MessageFns<Friend> = {
  encode(message: Friend, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.friend_id !== 0) {
      writer.uint32(16).uint64(message.friend_id);
    }
    if (message.remark !== "") {
      writer.uint32(26).string(message.remark);
    }
    if (message.source !== 0) {
      writer.uint32(32).int32(message.source);
    }
    if (message.blocked !== false) {
      writer.uint32(40).bool(message.blocked);
    }
    if (message.starred !== false) {
      writer.uint32(48).bool(message.starred);
    }
    if (message.create_time !== 0) {
      writer.uint32(56).int64(message.create_time);
    }
    if (message.extra !== "") {
      writer.uint32(66).string(message.extra);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Friend {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFriend();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.friend_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.remark = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.source = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.blocked = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.starred = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.extra = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Friend {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      friend_id: isSet(object.friendId)
        ? globalThis.Number(object.friendId)
        : isSet(object.friend_id)
        ? globalThis.Number(object.friend_id)
        : 0,
      remark: isSet(object.remark) ? globalThis.String(object.remark) : "",
      source: isSet(object.source) ? globalThis.Number(object.source) : 0,
      blocked: isSet(object.blocked) ? globalThis.Boolean(object.blocked) : false,
      starred: isSet(object.starred) ? globalThis.Boolean(object.starred) : false,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      extra: isSet(object.extra) ? globalThis.String(object.extra) : "",
    };
  },

  toJSON(message: Friend): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.friend_id !== 0) {
      obj.friendId = Math.round(message.friend_id);
    }
    if (message.remark !== "") {
      obj.remark = message.remark;
    }
    if (message.source !== 0) {
      obj.source = Math.round(message.source);
    }
    if (message.blocked !== false) {
      obj.blocked = message.blocked;
    }
    if (message.starred !== false) {
      obj.starred = message.starred;
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.extra !== "") {
      obj.extra = message.extra;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Friend>, I>>(base?: I): Friend {
    return Friend.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Friend>, I>>(object: I): Friend {
    const message = createBaseFriend();
    message.user_id = object.user_id ?? 0;
    message.friend_id = object.friend_id ?? 0;
    message.remark = object.remark ?? "";
    message.source = object.source ?? 0;
    message.blocked = object.blocked ?? false;
    message.starred = object.starred ?? false;
    message.create_time = object.create_time ?? 0;
    message.extra = object.extra ?? "";
    return message;
  },
};

function createBaseFriendRequest(): FriendRequest {
  return {
    id: 0,
    from_user_id: 0,
    to_user_id: 0,
    apply_msg: "",
    status: 0,
    source: 0,
    request_time: 0,
    handle_time: 0,
    reject_reason: "",
  };
}

export const FriendRequest: MessageFns<FriendRequest> = {
  encode(message: FriendRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.from_user_id !== 0) {
      writer.uint32(16).uint64(message.from_user_id);
    }
    if (message.to_user_id !== 0) {
      writer.uint32(24).uint64(message.to_user_id);
    }
    if (message.apply_msg !== "") {
      writer.uint32(34).string(message.apply_msg);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.source !== 0) {
      writer.uint32(48).int32(message.source);
    }
    if (message.request_time !== 0) {
      writer.uint32(56).int64(message.request_time);
    }
    if (message.handle_time !== 0) {
      writer.uint32(64).int64(message.handle_time);
    }
    if (message.reject_reason !== "") {
      writer.uint32(74).string(message.reject_reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FriendRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFriendRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.from_user_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.to_user_id = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.apply_msg = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.source = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.request_time = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.handle_time = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.reject_reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FriendRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      from_user_id: isSet(object.fromUserId)
        ? globalThis.Number(object.fromUserId)
        : isSet(object.from_user_id)
        ? globalThis.Number(object.from_user_id)
        : 0,
      to_user_id: isSet(object.toUserId)
        ? globalThis.Number(object.toUserId)
        : isSet(object.to_user_id)
        ? globalThis.Number(object.to_user_id)
        : 0,
      apply_msg: isSet(object.applyMsg)
        ? globalThis.String(object.applyMsg)
        : isSet(object.apply_msg)
        ? globalThis.String(object.apply_msg)
        : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      source: isSet(object.source) ? globalThis.Number(object.source) : 0,
      request_time: isSet(object.requestTime)
        ? globalThis.Number(object.requestTime)
        : isSet(object.request_time)
        ? globalThis.Number(object.request_time)
        : 0,
      handle_time: isSet(object.handleTime)
        ? globalThis.Number(object.handleTime)
        : isSet(object.handle_time)
        ? globalThis.Number(object.handle_time)
        : 0,
      reject_reason: isSet(object.rejectReason)
        ? globalThis.String(object.rejectReason)
        : isSet(object.reject_reason)
        ? globalThis.String(object.reject_reason)
        : "",
    };
  },

  toJSON(message: FriendRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.from_user_id !== 0) {
      obj.fromUserId = Math.round(message.from_user_id);
    }
    if (message.to_user_id !== 0) {
      obj.toUserId = Math.round(message.to_user_id);
    }
    if (message.apply_msg !== "") {
      obj.applyMsg = message.apply_msg;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.source !== 0) {
      obj.source = Math.round(message.source);
    }
    if (message.request_time !== 0) {
      obj.requestTime = Math.round(message.request_time);
    }
    if (message.handle_time !== 0) {
      obj.handleTime = Math.round(message.handle_time);
    }
    if (message.reject_reason !== "") {
      obj.rejectReason = message.reject_reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FriendRequest>, I>>(base?: I): FriendRequest {
    return FriendRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FriendRequest>, I>>(object: I): FriendRequest {
    const message = createBaseFriendRequest();
    message.id = object.id ?? 0;
    message.from_user_id = object.from_user_id ?? 0;
    message.to_user_id = object.to_user_id ?? 0;
    message.apply_msg = object.apply_msg ?? "";
    message.status = object.status ?? 0;
    message.source = object.source ?? 0;
    message.request_time = object.request_time ?? 0;
    message.handle_time = object.handle_time ?? 0;
    message.reject_reason = object.reject_reason ?? "";
    return message;
  },
};

function createBaseGetUserInfoReq(): GetUserInfoReq {
  return { ids: [], phone: "", name: "", limit: 0, offset: 0 };
}

export const GetUserInfoReq: MessageFns<GetUserInfoReq> = {
  encode(message: GetUserInfoReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.ids) {
      writer.uint64(v);
    }
    writer.join();
    if (message.phone !== "") {
      writer.uint32(18).string(message.phone);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(40).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserInfoReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserInfoReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.ids.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ids.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserInfoReq {
    return {
      ids: globalThis.Array.isArray(object?.ids) ? object.ids.map((e: any) => globalThis.Number(e)) : [],
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: GetUserInfoReq): unknown {
    const obj: any = {};
    if (message.ids?.length) {
      obj.ids = message.ids.map((e) => Math.round(e));
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserInfoReq>, I>>(base?: I): GetUserInfoReq {
    return GetUserInfoReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserInfoReq>, I>>(object: I): GetUserInfoReq {
    const message = createBaseGetUserInfoReq();
    message.ids = object.ids?.map((e) => e) || [];
    message.phone = object.phone ?? "";
    message.name = object.name ?? "";
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseGetUserInfoResp(): GetUserInfoResp {
  return { data: [] };
}

export const GetUserInfoResp: MessageFns<GetUserInfoResp> = {
  encode(message: GetUserInfoResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      UserInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserInfoResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserInfoResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(UserInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserInfoResp {
    return { data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => UserInfo.fromJSON(e)) : [] };
  },

  toJSON(message: GetUserInfoResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => UserInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserInfoResp>, I>>(base?: I): GetUserInfoResp {
    return GetUserInfoResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserInfoResp>, I>>(object: I): GetUserInfoResp {
    const message = createBaseGetUserInfoResp();
    message.data = object.data?.map((e) => UserInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateInfoReq(): UpdateInfoReq {
  return { user_name: "", gender: 0, avatar: "", join_type: 0, personal_signature: "" };
}

export const UpdateInfoReq: MessageFns<UpdateInfoReq> = {
  encode(message: UpdateInfoReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_name !== "") {
      writer.uint32(10).string(message.user_name);
    }
    if (message.gender !== 0) {
      writer.uint32(16).int32(message.gender);
    }
    if (message.avatar !== "") {
      writer.uint32(26).string(message.avatar);
    }
    if (message.join_type !== 0) {
      writer.uint32(32).int32(message.join_type);
    }
    if (message.personal_signature !== "") {
      writer.uint32(42).string(message.personal_signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateInfoReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateInfoReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.gender = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.join_type = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.personal_signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateInfoReq {
    return {
      user_name: isSet(object.userName)
        ? globalThis.String(object.userName)
        : isSet(object.user_name)
        ? globalThis.String(object.user_name)
        : "",
      gender: isSet(object.gender) ? globalThis.Number(object.gender) : 0,
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      join_type: isSet(object.joinType)
        ? globalThis.Number(object.joinType)
        : isSet(object.join_type)
        ? globalThis.Number(object.join_type)
        : 0,
      personal_signature: isSet(object.personalSignature)
        ? globalThis.String(object.personalSignature)
        : isSet(object.personal_signature)
        ? globalThis.String(object.personal_signature)
        : "",
    };
  },

  toJSON(message: UpdateInfoReq): unknown {
    const obj: any = {};
    if (message.user_name !== "") {
      obj.userName = message.user_name;
    }
    if (message.gender !== 0) {
      obj.gender = Math.round(message.gender);
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.join_type !== 0) {
      obj.joinType = Math.round(message.join_type);
    }
    if (message.personal_signature !== "") {
      obj.personalSignature = message.personal_signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateInfoReq>, I>>(base?: I): UpdateInfoReq {
    return UpdateInfoReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateInfoReq>, I>>(object: I): UpdateInfoReq {
    const message = createBaseUpdateInfoReq();
    message.user_name = object.user_name ?? "";
    message.gender = object.gender ?? 0;
    message.avatar = object.avatar ?? "";
    message.join_type = object.join_type ?? 0;
    message.personal_signature = object.personal_signature ?? "";
    return message;
  },
};

function createBaseGetFriendsReq(): GetFriendsReq {
  return {};
}

export const GetFriendsReq: MessageFns<GetFriendsReq> = {
  encode(_: GetFriendsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFriendsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFriendsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetFriendsReq {
    return {};
  },

  toJSON(_: GetFriendsReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFriendsReq>, I>>(base?: I): GetFriendsReq {
    return GetFriendsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFriendsReq>, I>>(_: I): GetFriendsReq {
    const message = createBaseGetFriendsReq();
    return message;
  },
};

function createBaseGetFriendsResp(): GetFriendsResp {
  return { data: [] };
}

export const GetFriendsResp: MessageFns<GetFriendsResp> = {
  encode(message: GetFriendsResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      Friend.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFriendsResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFriendsResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(Friend.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFriendsResp {
    return { data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => Friend.fromJSON(e)) : [] };
  },

  toJSON(message: GetFriendsResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => Friend.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFriendsResp>, I>>(base?: I): GetFriendsResp {
    return GetFriendsResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFriendsResp>, I>>(object: I): GetFriendsResp {
    const message = createBaseGetFriendsResp();
    message.data = object.data?.map((e) => Friend.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateFriendReq(): CreateFriendReq {
  return { friend_id: 0, source: 0, remark: "" };
}

export const CreateFriendReq: MessageFns<CreateFriendReq> = {
  encode(message: CreateFriendReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.friend_id !== 0) {
      writer.uint32(8).uint64(message.friend_id);
    }
    if (message.source !== 0) {
      writer.uint32(16).int32(message.source);
    }
    if (message.remark !== "") {
      writer.uint32(26).string(message.remark);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateFriendReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateFriendReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.friend_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.source = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.remark = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateFriendReq {
    return {
      friend_id: isSet(object.friendId)
        ? globalThis.Number(object.friendId)
        : isSet(object.friend_id)
        ? globalThis.Number(object.friend_id)
        : 0,
      source: isSet(object.source) ? globalThis.Number(object.source) : 0,
      remark: isSet(object.remark) ? globalThis.String(object.remark) : "",
    };
  },

  toJSON(message: CreateFriendReq): unknown {
    const obj: any = {};
    if (message.friend_id !== 0) {
      obj.friendId = Math.round(message.friend_id);
    }
    if (message.source !== 0) {
      obj.source = Math.round(message.source);
    }
    if (message.remark !== "") {
      obj.remark = message.remark;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateFriendReq>, I>>(base?: I): CreateFriendReq {
    return CreateFriendReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateFriendReq>, I>>(object: I): CreateFriendReq {
    const message = createBaseCreateFriendReq();
    message.friend_id = object.friend_id ?? 0;
    message.source = object.source ?? 0;
    message.remark = object.remark ?? "";
    return message;
  },
};

function createBaseUpdateFriendReq(): UpdateFriendReq {
  return { friend_id: 0, remark: "", blocked: false, starred: false };
}

export const UpdateFriendReq: MessageFns<UpdateFriendReq> = {
  encode(message: UpdateFriendReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.friend_id !== 0) {
      writer.uint32(8).uint64(message.friend_id);
    }
    if (message.remark !== "") {
      writer.uint32(18).string(message.remark);
    }
    if (message.blocked !== false) {
      writer.uint32(24).bool(message.blocked);
    }
    if (message.starred !== false) {
      writer.uint32(32).bool(message.starred);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateFriendReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateFriendReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.friend_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.remark = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.blocked = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.starred = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateFriendReq {
    return {
      friend_id: isSet(object.friendId)
        ? globalThis.Number(object.friendId)
        : isSet(object.friend_id)
        ? globalThis.Number(object.friend_id)
        : 0,
      remark: isSet(object.remark) ? globalThis.String(object.remark) : "",
      blocked: isSet(object.blocked) ? globalThis.Boolean(object.blocked) : false,
      starred: isSet(object.starred) ? globalThis.Boolean(object.starred) : false,
    };
  },

  toJSON(message: UpdateFriendReq): unknown {
    const obj: any = {};
    if (message.friend_id !== 0) {
      obj.friendId = Math.round(message.friend_id);
    }
    if (message.remark !== "") {
      obj.remark = message.remark;
    }
    if (message.blocked !== false) {
      obj.blocked = message.blocked;
    }
    if (message.starred !== false) {
      obj.starred = message.starred;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateFriendReq>, I>>(base?: I): UpdateFriendReq {
    return UpdateFriendReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateFriendReq>, I>>(object: I): UpdateFriendReq {
    const message = createBaseUpdateFriendReq();
    message.friend_id = object.friend_id ?? 0;
    message.remark = object.remark ?? "";
    message.blocked = object.blocked ?? false;
    message.starred = object.starred ?? false;
    return message;
  },
};

function createBaseDeleteFriendReq(): DeleteFriendReq {
  return { friend_id: 0 };
}

export const DeleteFriendReq: MessageFns<DeleteFriendReq> = {
  encode(message: DeleteFriendReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.friend_id !== 0) {
      writer.uint32(8).uint64(message.friend_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteFriendReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteFriendReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.friend_id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteFriendReq {
    return {
      friend_id: isSet(object.friendId)
        ? globalThis.Number(object.friendId)
        : isSet(object.friend_id)
        ? globalThis.Number(object.friend_id)
        : 0,
    };
  },

  toJSON(message: DeleteFriendReq): unknown {
    const obj: any = {};
    if (message.friend_id !== 0) {
      obj.friendId = Math.round(message.friend_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteFriendReq>, I>>(base?: I): DeleteFriendReq {
    return DeleteFriendReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteFriendReq>, I>>(object: I): DeleteFriendReq {
    const message = createBaseDeleteFriendReq();
    message.friend_id = object.friend_id ?? 0;
    return message;
  },
};

function createBaseNewFriendApplyReq(): NewFriendApplyReq {
  return { to_user_id: 0, apply_msg: "", source: 0 };
}

export const NewFriendApplyReq: MessageFns<NewFriendApplyReq> = {
  encode(message: NewFriendApplyReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to_user_id !== 0) {
      writer.uint32(8).uint64(message.to_user_id);
    }
    if (message.apply_msg !== "") {
      writer.uint32(18).string(message.apply_msg);
    }
    if (message.source !== 0) {
      writer.uint32(24).int32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewFriendApplyReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewFriendApplyReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.to_user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.apply_msg = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.source = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewFriendApplyReq {
    return {
      to_user_id: isSet(object.toUserId)
        ? globalThis.Number(object.toUserId)
        : isSet(object.to_user_id)
        ? globalThis.Number(object.to_user_id)
        : 0,
      apply_msg: isSet(object.applyMsg)
        ? globalThis.String(object.applyMsg)
        : isSet(object.apply_msg)
        ? globalThis.String(object.apply_msg)
        : "",
      source: isSet(object.source) ? globalThis.Number(object.source) : 0,
    };
  },

  toJSON(message: NewFriendApplyReq): unknown {
    const obj: any = {};
    if (message.to_user_id !== 0) {
      obj.toUserId = Math.round(message.to_user_id);
    }
    if (message.apply_msg !== "") {
      obj.applyMsg = message.apply_msg;
    }
    if (message.source !== 0) {
      obj.source = Math.round(message.source);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NewFriendApplyReq>, I>>(base?: I): NewFriendApplyReq {
    return NewFriendApplyReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewFriendApplyReq>, I>>(object: I): NewFriendApplyReq {
    const message = createBaseNewFriendApplyReq();
    message.to_user_id = object.to_user_id ?? 0;
    message.apply_msg = object.apply_msg ?? "";
    message.source = object.source ?? 0;
    return message;
  },
};

function createBaseNewFriendApplyResp(): NewFriendApplyResp {
  return { data: undefined };
}

export const NewFriendApplyResp: MessageFns<NewFriendApplyResp> = {
  encode(message: NewFriendApplyResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      FriendRequest.encode(message.data, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewFriendApplyResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewFriendApplyResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = FriendRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewFriendApplyResp {
    return { data: isSet(object.data) ? FriendRequest.fromJSON(object.data) : undefined };
  },

  toJSON(message: NewFriendApplyResp): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = FriendRequest.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NewFriendApplyResp>, I>>(base?: I): NewFriendApplyResp {
    return NewFriendApplyResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewFriendApplyResp>, I>>(object: I): NewFriendApplyResp {
    const message = createBaseNewFriendApplyResp();
    message.data = (object.data !== undefined && object.data !== null)
      ? FriendRequest.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseHandleFriendApplyReq(): HandleFriendApplyReq {
  return { request_id: 0, result: 0, reject_reason: "" };
}

export const HandleFriendApplyReq: MessageFns<HandleFriendApplyReq> = {
  encode(message: HandleFriendApplyReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.request_id !== 0) {
      writer.uint32(8).uint64(message.request_id);
    }
    if (message.result !== 0) {
      writer.uint32(16).int32(message.result);
    }
    if (message.reject_reason !== "") {
      writer.uint32(26).string(message.reject_reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HandleFriendApplyReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHandleFriendApplyReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.request_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.result = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reject_reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HandleFriendApplyReq {
    return {
      request_id: isSet(object.requestId)
        ? globalThis.Number(object.requestId)
        : isSet(object.request_id)
        ? globalThis.Number(object.request_id)
        : 0,
      result: isSet(object.result) ? globalThis.Number(object.result) : 0,
      reject_reason: isSet(object.rejectReason)
        ? globalThis.String(object.rejectReason)
        : isSet(object.reject_reason)
        ? globalThis.String(object.reject_reason)
        : "",
    };
  },

  toJSON(message: HandleFriendApplyReq): unknown {
    const obj: any = {};
    if (message.request_id !== 0) {
      obj.requestId = Math.round(message.request_id);
    }
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    if (message.reject_reason !== "") {
      obj.rejectReason = message.reject_reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandleFriendApplyReq>, I>>(base?: I): HandleFriendApplyReq {
    return HandleFriendApplyReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandleFriendApplyReq>, I>>(object: I): HandleFriendApplyReq {
    const message = createBaseHandleFriendApplyReq();
    message.request_id = object.request_id ?? 0;
    message.result = object.result ?? 0;
    message.reject_reason = object.reject_reason ?? "";
    return message;
  },
};

function createBaseGetPendingFriendAppliesReq(): GetPendingFriendAppliesReq {
  return {};
}

export const GetPendingFriendAppliesReq: MessageFns<GetPendingFriendAppliesReq> = {
  encode(_: GetPendingFriendAppliesReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPendingFriendAppliesReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPendingFriendAppliesReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetPendingFriendAppliesReq {
    return {};
  },

  toJSON(_: GetPendingFriendAppliesReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPendingFriendAppliesReq>, I>>(base?: I): GetPendingFriendAppliesReq {
    return GetPendingFriendAppliesReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPendingFriendAppliesReq>, I>>(_: I): GetPendingFriendAppliesReq {
    const message = createBaseGetPendingFriendAppliesReq();
    return message;
  },
};

function createBaseGetPendingFriendAppliesResp(): GetPendingFriendAppliesResp {
  return { data: [] };
}

export const GetPendingFriendAppliesResp: MessageFns<GetPendingFriendAppliesResp> = {
  encode(message: GetPendingFriendAppliesResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      FriendRequest.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPendingFriendAppliesResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPendingFriendAppliesResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(FriendRequest.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPendingFriendAppliesResp {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => FriendRequest.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetPendingFriendAppliesResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => FriendRequest.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPendingFriendAppliesResp>, I>>(base?: I): GetPendingFriendAppliesResp {
    return GetPendingFriendAppliesResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPendingFriendAppliesResp>, I>>(object: I): GetPendingFriendAppliesResp {
    const message = createBaseGetPendingFriendAppliesResp();
    message.data = object.data?.map((e) => FriendRequest.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSearchFriendReq(): SearchFriendReq {
  return { name: "", id: 0, phone: "", limit: 0, offset: 0 };
}

export const SearchFriendReq: MessageFns<SearchFriendReq> = {
  encode(message: SearchFriendReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.phone !== "") {
      writer.uint32(26).string(message.phone);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(40).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchFriendReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchFriendReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchFriendReq {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: SearchFriendReq): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchFriendReq>, I>>(base?: I): SearchFriendReq {
    return SearchFriendReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchFriendReq>, I>>(object: I): SearchFriendReq {
    const message = createBaseSearchFriendReq();
    message.name = object.name ?? "";
    message.id = object.id ?? 0;
    message.phone = object.phone ?? "";
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseSearchFriendResp(): SearchFriendResp {
  return { data: [], total: 0 };
}

export const SearchFriendResp: MessageFns<SearchFriendResp> = {
  encode(message: SearchFriendResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      UserInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int64(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchFriendResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchFriendResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(UserInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchFriendResp {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => UserInfo.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: SearchFriendResp): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => UserInfo.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchFriendResp>, I>>(base?: I): SearchFriendResp {
    return SearchFriendResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchFriendResp>, I>>(object: I): SearchFriendResp {
    const message = createBaseSearchFriendResp();
    message.data = object.data?.map((e) => UserInfo.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
