// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.31.1
// source: proto/group/group.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "grouppb";

export enum GroupRole {
  /** GROUP_ROLE_UNSPECIFIED - 未知 */
  GROUP_ROLE_UNSPECIFIED = 0,
  /** GROUP_ROLE_OWNER - 群主 */
  GROUP_ROLE_OWNER = 1,
  /** GROUP_ROLE_ADMIN - 管理员 */
  GROUP_ROLE_ADMIN = 2,
  /** GROUP_ROLE_MEMBER - 普通成员 */
  GROUP_ROLE_MEMBER = 3,
  UNRECOGNIZED = -1,
}

export function groupRoleFromJSON(object: any): GroupRole {
  switch (object) {
    case 0:
    case "GROUP_ROLE_UNSPECIFIED":
      return GroupRole.GROUP_ROLE_UNSPECIFIED;
    case 1:
    case "GROUP_ROLE_OWNER":
      return GroupRole.GROUP_ROLE_OWNER;
    case 2:
    case "GROUP_ROLE_ADMIN":
      return GroupRole.GROUP_ROLE_ADMIN;
    case 3:
    case "GROUP_ROLE_MEMBER":
      return GroupRole.GROUP_ROLE_MEMBER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GroupRole.UNRECOGNIZED;
  }
}

export function groupRoleToJSON(object: GroupRole): string {
  switch (object) {
    case GroupRole.GROUP_ROLE_UNSPECIFIED:
      return "GROUP_ROLE_UNSPECIFIED";
    case GroupRole.GROUP_ROLE_OWNER:
      return "GROUP_ROLE_OWNER";
    case GroupRole.GROUP_ROLE_ADMIN:
      return "GROUP_ROLE_ADMIN";
    case GroupRole.GROUP_ROLE_MEMBER:
      return "GROUP_ROLE_MEMBER";
    case GroupRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum JoinType {
  JOIN_TYPE_UNSPECIFIED = 0,
  /** JOIN_TYPE_AFTER_APPROVAL - 同意后加入 */
  JOIN_TYPE_AFTER_APPROVAL = 1,
  /** JOIN_TYPE_DIRECT - 直接加入 */
  JOIN_TYPE_DIRECT = 2,
  UNRECOGNIZED = -1,
}

export function joinTypeFromJSON(object: any): JoinType {
  switch (object) {
    case 0:
    case "JOIN_TYPE_UNSPECIFIED":
      return JoinType.JOIN_TYPE_UNSPECIFIED;
    case 1:
    case "JOIN_TYPE_AFTER_APPROVAL":
      return JoinType.JOIN_TYPE_AFTER_APPROVAL;
    case 2:
    case "JOIN_TYPE_DIRECT":
      return JoinType.JOIN_TYPE_DIRECT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JoinType.UNRECOGNIZED;
  }
}

export function joinTypeToJSON(object: JoinType): string {
  switch (object) {
    case JoinType.JOIN_TYPE_UNSPECIFIED:
      return "JOIN_TYPE_UNSPECIFIED";
    case JoinType.JOIN_TYPE_AFTER_APPROVAL:
      return "JOIN_TYPE_AFTER_APPROVAL";
    case JoinType.JOIN_TYPE_DIRECT:
      return "JOIN_TYPE_DIRECT";
    case JoinType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 群组信息 */
export interface GroupInfo {
  /** 群组ID */
  id: number;
  /** 群主ID */
  owner_id: number;
  /** 群组名称 */
  name: string;
  /** 群头像 */
  avatar: string;
  /** 群公告 */
  notice: string;
  /** 加群方式 */
  join_type: JoinType;
  /** 成员数量 */
  member_count: number;
  /** 创建时间 */
  create_time: number;
  /** 更新时间 */
  update_time: number;
}

/** 群成员信息 */
export interface GroupMember {
  /** 群组ID */
  group_id: number;
  /** 用户ID */
  user_id: number;
  /** 群角色 */
  role: GroupRole;
  /** 群昵称 */
  nickname: string;
  /** 禁言截止时间 */
  mute_until: number;
  /** 加入时间 */
  joined_at: number;
  /** 扩展字段 */
  extra: string;
}

function createBaseGroupInfo(): GroupInfo {
  return {
    id: 0,
    owner_id: 0,
    name: "",
    avatar: "",
    notice: "",
    join_type: 0,
    member_count: 0,
    create_time: 0,
    update_time: 0,
  };
}

export const GroupInfo: MessageFns<GroupInfo> = {
  encode(message: GroupInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.owner_id !== 0) {
      writer.uint32(16).uint64(message.owner_id);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.avatar !== "") {
      writer.uint32(34).string(message.avatar);
    }
    if (message.notice !== "") {
      writer.uint32(42).string(message.notice);
    }
    if (message.join_type !== 0) {
      writer.uint32(48).int32(message.join_type);
    }
    if (message.member_count !== 0) {
      writer.uint32(56).int32(message.member_count);
    }
    if (message.create_time !== 0) {
      writer.uint32(64).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(72).int64(message.update_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.owner_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.join_type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.member_count = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupInfo {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      owner_id: isSet(object.ownerId)
        ? globalThis.Number(object.ownerId)
        : isSet(object.owner_id)
        ? globalThis.Number(object.owner_id)
        : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
      join_type: isSet(object.joinType)
        ? joinTypeFromJSON(object.joinType)
        : isSet(object.join_type)
        ? joinTypeFromJSON(object.join_type)
        : 0,
      member_count: isSet(object.memberCount)
        ? globalThis.Number(object.memberCount)
        : isSet(object.member_count)
        ? globalThis.Number(object.member_count)
        : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
    };
  },

  toJSON(message: GroupInfo): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.owner_id !== 0) {
      obj.ownerId = Math.round(message.owner_id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    if (message.join_type !== 0) {
      obj.joinType = joinTypeToJSON(message.join_type);
    }
    if (message.member_count !== 0) {
      obj.memberCount = Math.round(message.member_count);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupInfo>, I>>(base?: I): GroupInfo {
    return GroupInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupInfo>, I>>(object: I): GroupInfo {
    const message = createBaseGroupInfo();
    message.id = object.id ?? 0;
    message.owner_id = object.owner_id ?? 0;
    message.name = object.name ?? "";
    message.avatar = object.avatar ?? "";
    message.notice = object.notice ?? "";
    message.join_type = object.join_type ?? 0;
    message.member_count = object.member_count ?? 0;
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    return message;
  },
};

function createBaseGroupMember(): GroupMember {
  return { group_id: 0, user_id: 0, role: 0, nickname: "", mute_until: 0, joined_at: 0, extra: "" };
}

export const GroupMember: MessageFns<GroupMember> = {
  encode(message: GroupMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== 0) {
      writer.uint32(8).uint64(message.group_id);
    }
    if (message.user_id !== 0) {
      writer.uint32(16).uint64(message.user_id);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    if (message.nickname !== "") {
      writer.uint32(34).string(message.nickname);
    }
    if (message.mute_until !== 0) {
      writer.uint32(40).int64(message.mute_until);
    }
    if (message.joined_at !== 0) {
      writer.uint32(64).int64(message.joined_at);
    }
    if (message.extra !== "") {
      writer.uint32(74).string(message.extra);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.group_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.mute_until = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.joined_at = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.extra = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupMember {
    return {
      group_id: isSet(object.groupId)
        ? globalThis.Number(object.groupId)
        : isSet(object.group_id)
        ? globalThis.Number(object.group_id)
        : 0,
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      role: isSet(object.role) ? groupRoleFromJSON(object.role) : 0,
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      mute_until: isSet(object.muteUntil)
        ? globalThis.Number(object.muteUntil)
        : isSet(object.mute_until)
        ? globalThis.Number(object.mute_until)
        : 0,
      joined_at: isSet(object.joinedAt)
        ? globalThis.Number(object.joinedAt)
        : isSet(object.joined_at)
        ? globalThis.Number(object.joined_at)
        : 0,
      extra: isSet(object.extra) ? globalThis.String(object.extra) : "",
    };
  },

  toJSON(message: GroupMember): unknown {
    const obj: any = {};
    if (message.group_id !== 0) {
      obj.groupId = Math.round(message.group_id);
    }
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.role !== 0) {
      obj.role = groupRoleToJSON(message.role);
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.mute_until !== 0) {
      obj.muteUntil = Math.round(message.mute_until);
    }
    if (message.joined_at !== 0) {
      obj.joinedAt = Math.round(message.joined_at);
    }
    if (message.extra !== "") {
      obj.extra = message.extra;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupMember>, I>>(base?: I): GroupMember {
    return GroupMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupMember>, I>>(object: I): GroupMember {
    const message = createBaseGroupMember();
    message.group_id = object.group_id ?? 0;
    message.user_id = object.user_id ?? 0;
    message.role = object.role ?? 0;
    message.nickname = object.nickname ?? "";
    message.mute_until = object.mute_until ?? 0;
    message.joined_at = object.joined_at ?? 0;
    message.extra = object.extra ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
