// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.31.1
// source: apis/message/message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types";

/** Message */
export interface Message {
  /** @gotags: json:"msg_id" */
  msg_id: string;
  /** @gotags: json:"client_id" */
  client_id: string;
  /** @gotags: json:"session_id" */
  session_id: string;
  /** @gotags: json:"from_user_id" */
  from_user_id: number;
  /** @gotags: json:"msg_type" */
  msg_type: number;
  /** @gotags: json:"seq" */
  seq: string;
  /** @gotags: json:"content" */
  content: string;
  /** @gotags: json:"media_url" */
  media_url: string;
  /** @gotags: json:"extra" */
  extra: string;
  /** @gotags: json:"status" */
  status: number;
  /** @gotags: json:"create_time" */
  create_time: number;
}

export interface Session {
  /** @gotags: json:"session_id" */
  session_id: string;
  /** @gotags: json:"type" */
  type: number;
  /** @gotags: json:"session_key" */
  session_key: string;
  /** @gotags: json:"max_seq" */
  max_seq: string;
  /** @gotags: json:"actual_seq" */
  actual_seq: string;
  /** @gotags: json:"last_content" */
  last_content: string;
  /** @gotags: json:"last_sender" */
  last_sender: number;
  /** @gotags: json:"create_time" */
  create_time: number;
  /** @gotags: json:"update_time" */
  update_time: number;
}

/** UserSession */
export interface UserSession {
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"session_id" */
  session_id: string;
  /** @gotags: json:"is_top" */
  is_top: number;
  /** @gotags: json:"is_disturb" */
  is_disturb: number;
  /** @gotags: json:"last_read_seq" */
  last_read_seq: string;
  /** @gotags: json:"create_time" */
  create_time: number;
  /** @gotags: json:"update_time" */
  update_time: number;
  /** @gotags: json:"unread_count" */
  unread_count: number;
}

/** GetHistoryReq */
export interface GetHistoryReq {
  /** @gotags: form:"session_id,optional" json:"session_id,optional" */
  session_id: string;
  /** @gotags: form:"start_seq,optional" json:"start_seq,optional" */
  start_seq: string;
  /** @gotags: form:"end_seq,optional" json:"end_seq,optional" */
  end_seq: string;
  /** @gotags: form:"limit,optional,default=20" json:"limit,optional" */
  limit: number;
}

/** GetHistoryResp */
export interface GetHistoryResp {
  /** @gotags: json:"list" */
  list: Message[];
}

/** UpdateSessionReq */
export interface UpdateSessionReq {
  /** @gotags: json:"session_id" */
  session_id: string;
  /** @gotags: json:"session_key" */
  session_key: string;
  /** @gotags: json:"is_top,optional" */
  is_top: number;
  /** @gotags: json:"is_disturb,optional" */
  is_disturb: number;
}

/** GetUserSessionsResp */
export interface GetUserSessionsResp {
  /** @gotags: json:"sessions" */
  sessions: UserSession[];
}

export interface GetUserActiveSessionsReq {
  /** @gotags: form:"timestamp,optional" json:"timestamp,optional" */
  timestamp: number;
}

export interface GetUserActiveSessionsResp {
  /** @gotags: json:"sessions" */
  sessions: Session[];
}

/** MarkSessionReadReq 上报会话已读游标 */
export interface MarkSessionReadReq {
  /** @gotags: json:"session_id" */
  session_id: string;
  /** @gotags: json:"read_seq" */
  read_seq: string;
}

/** RecallMessageReq 撤回消息（操作者由服务端从 JWT 解析） */
export interface RecallMessageReq {
  /** @gotags: json:"msg_id" */
  msg_id: string;
  /** @gotags: json:"session_id" */
  session_id: string;
}

export interface RecallMessageResp {
}

/** GetSessionReq 根据 session_id 或 session_key 查询会话 */
export interface GetSessionReq {
  /** @gotags: form:"session_id,optional" json:"session_id,optional" */
  session_id: string;
  /** @gotags: form:"session_key,optional" json:"session_key,optional" */
  session_key: string;
  /** @gotags: form:"session_type,optional" json:"session_type,optional" */
  session_type: number;
}

/** GetSessionResp */
export interface GetSessionResp {
  /** @gotags: json:"session" */
  session: Session | undefined;
}

function createBaseMessage(): Message {
  return {
    msg_id: "",
    client_id: "",
    session_id: "",
    from_user_id: 0,
    msg_type: 0,
    seq: "0",
    content: "",
    media_url: "",
    extra: "",
    status: 0,
    create_time: 0,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg_id !== "") {
      writer.uint32(10).string(message.msg_id);
    }
    if (message.client_id !== "") {
      writer.uint32(18).string(message.client_id);
    }
    if (message.session_id !== "") {
      writer.uint32(26).string(message.session_id);
    }
    if (message.from_user_id !== 0) {
      writer.uint32(32).uint64(message.from_user_id);
    }
    if (message.msg_type !== 0) {
      writer.uint32(40).int32(message.msg_type);
    }
    if (message.seq !== "0") {
      writer.uint32(48).uint64(message.seq);
    }
    if (message.content !== "") {
      writer.uint32(58).string(message.content);
    }
    if (message.media_url !== "") {
      writer.uint32(66).string(message.media_url);
    }
    if (message.extra !== "") {
      writer.uint32(74).string(message.extra);
    }
    if (message.status !== 0) {
      writer.uint32(80).int32(message.status);
    }
    if (message.create_time !== 0) {
      writer.uint32(88).int64(message.create_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.client_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.from_user_id = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.msg_type = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.seq = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.media_url = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.extra = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      msg_id: isSet(object.msgId)
        ? globalThis.String(object.msgId)
        : isSet(object.msg_id)
        ? globalThis.String(object.msg_id)
        : "",
      client_id: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      from_user_id: isSet(object.fromUserId)
        ? globalThis.Number(object.fromUserId)
        : isSet(object.from_user_id)
        ? globalThis.Number(object.from_user_id)
        : 0,
      msg_type: isSet(object.msgType)
        ? globalThis.Number(object.msgType)
        : isSet(object.msg_type)
        ? globalThis.Number(object.msg_type)
        : 0,
      seq: isSet(object.seq) ? globalThis.String(object.seq) : "0",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      media_url: isSet(object.mediaUrl)
        ? globalThis.String(object.mediaUrl)
        : isSet(object.media_url)
        ? globalThis.String(object.media_url)
        : "",
      extra: isSet(object.extra) ? globalThis.String(object.extra) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.msg_id !== "") {
      obj.msgId = message.msg_id;
    }
    if (message.client_id !== "") {
      obj.clientId = message.client_id;
    }
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.from_user_id !== 0) {
      obj.fromUserId = Math.round(message.from_user_id);
    }
    if (message.msg_type !== 0) {
      obj.msgType = Math.round(message.msg_type);
    }
    if (message.seq !== "0") {
      obj.seq = globalThis.String(message.seq);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.media_url !== "") {
      obj.mediaUrl = message.media_url;
    }
    if (message.extra !== "") {
      obj.extra = message.extra;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.msg_id = object.msg_id ?? "";
    message.client_id = object.client_id ?? "";
    message.session_id = object.session_id ?? "";
    message.from_user_id = object.from_user_id ?? 0;
    message.msg_type = object.msg_type ?? 0;
    message.seq = object.seq ?? "0";
    message.content = object.content ?? "";
    message.media_url = object.media_url ?? "";
    message.extra = object.extra ?? "";
    message.status = object.status ?? 0;
    message.create_time = object.create_time ?? 0;
    return message;
  },
};

function createBaseSession(): Session {
  return {
    session_id: "",
    type: 0,
    session_key: "",
    max_seq: "0",
    actual_seq: "0",
    last_content: "",
    last_sender: 0,
    create_time: 0,
    update_time: 0,
  };
}

export const Session: MessageFns<Session> = {
  encode(message: Session, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.session_key !== "") {
      writer.uint32(26).string(message.session_key);
    }
    if (message.max_seq !== "0") {
      writer.uint32(32).uint64(message.max_seq);
    }
    if (message.actual_seq !== "0") {
      writer.uint32(40).uint64(message.actual_seq);
    }
    if (message.last_content !== "") {
      writer.uint32(50).string(message.last_content);
    }
    if (message.last_sender !== 0) {
      writer.uint32(56).uint64(message.last_sender);
    }
    if (message.create_time !== 0) {
      writer.uint32(64).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(72).int64(message.update_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Session {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.session_key = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.max_seq = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.actual_seq = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.last_content = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.last_sender = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      session_key: isSet(object.sessionKey)
        ? globalThis.String(object.sessionKey)
        : isSet(object.session_key)
        ? globalThis.String(object.session_key)
        : "",
      max_seq: isSet(object.maxSeq)
        ? globalThis.String(object.maxSeq)
        : isSet(object.max_seq)
        ? globalThis.String(object.max_seq)
        : "0",
      actual_seq: isSet(object.actualSeq)
        ? globalThis.String(object.actualSeq)
        : isSet(object.actual_seq)
        ? globalThis.String(object.actual_seq)
        : "0",
      last_content: isSet(object.lastContent)
        ? globalThis.String(object.lastContent)
        : isSet(object.last_content)
        ? globalThis.String(object.last_content)
        : "",
      last_sender: isSet(object.lastSender)
        ? globalThis.Number(object.lastSender)
        : isSet(object.last_sender)
        ? globalThis.Number(object.last_sender)
        : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.session_key !== "") {
      obj.sessionKey = message.session_key;
    }
    if (message.max_seq !== "0") {
      obj.maxSeq = globalThis.String(message.max_seq);
    }
    if (message.actual_seq !== "0") {
      obj.actualSeq = globalThis.String(message.actual_seq);
    }
    if (message.last_content !== "") {
      obj.lastContent = message.last_content;
    }
    if (message.last_sender !== 0) {
      obj.lastSender = Math.round(message.last_sender);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Session>, I>>(base?: I): Session {
    return Session.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Session>, I>>(object: I): Session {
    const message = createBaseSession();
    message.session_id = object.session_id ?? "";
    message.type = object.type ?? 0;
    message.session_key = object.session_key ?? "";
    message.max_seq = object.max_seq ?? "0";
    message.actual_seq = object.actual_seq ?? "0";
    message.last_content = object.last_content ?? "";
    message.last_sender = object.last_sender ?? 0;
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    return message;
  },
};

function createBaseUserSession(): UserSession {
  return {
    user_id: 0,
    session_id: "",
    is_top: 0,
    is_disturb: 0,
    last_read_seq: "0",
    create_time: 0,
    update_time: 0,
    unread_count: 0,
  };
}

export const UserSession: MessageFns<UserSession> = {
  encode(message: UserSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.session_id !== "") {
      writer.uint32(18).string(message.session_id);
    }
    if (message.is_top !== 0) {
      writer.uint32(24).int32(message.is_top);
    }
    if (message.is_disturb !== 0) {
      writer.uint32(32).int32(message.is_disturb);
    }
    if (message.last_read_seq !== "0") {
      writer.uint32(40).uint64(message.last_read_seq);
    }
    if (message.create_time !== 0) {
      writer.uint32(48).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(64).int64(message.update_time);
    }
    if (message.unread_count !== 0) {
      writer.uint32(72).uint64(message.unread_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_top = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_disturb = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.last_read_seq = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.unread_count = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserSession {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      is_top: isSet(object.isTop)
        ? globalThis.Number(object.isTop)
        : isSet(object.is_top)
        ? globalThis.Number(object.is_top)
        : 0,
      is_disturb: isSet(object.isDisturb)
        ? globalThis.Number(object.isDisturb)
        : isSet(object.is_disturb)
        ? globalThis.Number(object.is_disturb)
        : 0,
      last_read_seq: isSet(object.lastReadSeq)
        ? globalThis.String(object.lastReadSeq)
        : isSet(object.last_read_seq)
        ? globalThis.String(object.last_read_seq)
        : "0",
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
      unread_count: isSet(object.unreadCount)
        ? globalThis.Number(object.unreadCount)
        : isSet(object.unread_count)
        ? globalThis.Number(object.unread_count)
        : 0,
    };
  },

  toJSON(message: UserSession): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.is_top !== 0) {
      obj.isTop = Math.round(message.is_top);
    }
    if (message.is_disturb !== 0) {
      obj.isDisturb = Math.round(message.is_disturb);
    }
    if (message.last_read_seq !== "0") {
      obj.lastReadSeq = globalThis.String(message.last_read_seq);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    if (message.unread_count !== 0) {
      obj.unreadCount = Math.round(message.unread_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserSession>, I>>(base?: I): UserSession {
    return UserSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserSession>, I>>(object: I): UserSession {
    const message = createBaseUserSession();
    message.user_id = object.user_id ?? 0;
    message.session_id = object.session_id ?? "";
    message.is_top = object.is_top ?? 0;
    message.is_disturb = object.is_disturb ?? 0;
    message.last_read_seq = object.last_read_seq ?? "0";
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    message.unread_count = object.unread_count ?? 0;
    return message;
  },
};

function createBaseGetHistoryReq(): GetHistoryReq {
  return { session_id: "", start_seq: "0", end_seq: "0", limit: 0 };
}

export const GetHistoryReq: MessageFns<GetHistoryReq> = {
  encode(message: GetHistoryReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.start_seq !== "0") {
      writer.uint32(16).int64(message.start_seq);
    }
    if (message.end_seq !== "0") {
      writer.uint32(24).int64(message.end_seq);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.start_seq = reader.int64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.end_seq = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryReq {
    return {
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      start_seq: isSet(object.startSeq)
        ? globalThis.String(object.startSeq)
        : isSet(object.start_seq)
        ? globalThis.String(object.start_seq)
        : "0",
      end_seq: isSet(object.endSeq)
        ? globalThis.String(object.endSeq)
        : isSet(object.end_seq)
        ? globalThis.String(object.end_seq)
        : "0",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetHistoryReq): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.start_seq !== "0") {
      obj.startSeq = globalThis.String(message.start_seq);
    }
    if (message.end_seq !== "0") {
      obj.endSeq = globalThis.String(message.end_seq);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryReq>, I>>(base?: I): GetHistoryReq {
    return GetHistoryReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryReq>, I>>(object: I): GetHistoryReq {
    const message = createBaseGetHistoryReq();
    message.session_id = object.session_id ?? "";
    message.start_seq = object.start_seq ?? "0";
    message.end_seq = object.end_seq ?? "0";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetHistoryResp(): GetHistoryResp {
  return { list: [] };
}

export const GetHistoryResp: MessageFns<GetHistoryResp> = {
  encode(message: GetHistoryResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(Message.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryResp {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => Message.fromJSON(e)) : [] };
  },

  toJSON(message: GetHistoryResp): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => Message.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryResp>, I>>(base?: I): GetHistoryResp {
    return GetHistoryResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryResp>, I>>(object: I): GetHistoryResp {
    const message = createBaseGetHistoryResp();
    message.list = object.list?.map((e) => Message.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateSessionReq(): UpdateSessionReq {
  return { session_id: "", session_key: "", is_top: 0, is_disturb: 0 };
}

export const UpdateSessionReq: MessageFns<UpdateSessionReq> = {
  encode(message: UpdateSessionReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.session_key !== "") {
      writer.uint32(18).string(message.session_key);
    }
    if (message.is_top !== 0) {
      writer.uint32(24).int32(message.is_top);
    }
    if (message.is_disturb !== 0) {
      writer.uint32(32).int32(message.is_disturb);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateSessionReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateSessionReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_top = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_disturb = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateSessionReq {
    return {
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      session_key: isSet(object.sessionKey)
        ? globalThis.String(object.sessionKey)
        : isSet(object.session_key)
        ? globalThis.String(object.session_key)
        : "",
      is_top: isSet(object.isTop)
        ? globalThis.Number(object.isTop)
        : isSet(object.is_top)
        ? globalThis.Number(object.is_top)
        : 0,
      is_disturb: isSet(object.isDisturb)
        ? globalThis.Number(object.isDisturb)
        : isSet(object.is_disturb)
        ? globalThis.Number(object.is_disturb)
        : 0,
    };
  },

  toJSON(message: UpdateSessionReq): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.session_key !== "") {
      obj.sessionKey = message.session_key;
    }
    if (message.is_top !== 0) {
      obj.isTop = Math.round(message.is_top);
    }
    if (message.is_disturb !== 0) {
      obj.isDisturb = Math.round(message.is_disturb);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateSessionReq>, I>>(base?: I): UpdateSessionReq {
    return UpdateSessionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateSessionReq>, I>>(object: I): UpdateSessionReq {
    const message = createBaseUpdateSessionReq();
    message.session_id = object.session_id ?? "";
    message.session_key = object.session_key ?? "";
    message.is_top = object.is_top ?? 0;
    message.is_disturb = object.is_disturb ?? 0;
    return message;
  },
};

function createBaseGetUserSessionsResp(): GetUserSessionsResp {
  return { sessions: [] };
}

export const GetUserSessionsResp: MessageFns<GetUserSessionsResp> = {
  encode(message: GetUserSessionsResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sessions) {
      UserSession.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserSessionsResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserSessionsResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessions.push(UserSession.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserSessionsResp {
    return {
      sessions: globalThis.Array.isArray(object?.sessions)
        ? object.sessions.map((e: any) => UserSession.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetUserSessionsResp): unknown {
    const obj: any = {};
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => UserSession.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserSessionsResp>, I>>(base?: I): GetUserSessionsResp {
    return GetUserSessionsResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserSessionsResp>, I>>(object: I): GetUserSessionsResp {
    const message = createBaseGetUserSessionsResp();
    message.sessions = object.sessions?.map((e) => UserSession.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetUserActiveSessionsReq(): GetUserActiveSessionsReq {
  return { timestamp: 0 };
}

export const GetUserActiveSessionsReq: MessageFns<GetUserActiveSessionsReq> = {
  encode(message: GetUserActiveSessionsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserActiveSessionsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserActiveSessionsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserActiveSessionsReq {
    return { timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0 };
  },

  toJSON(message: GetUserActiveSessionsReq): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserActiveSessionsReq>, I>>(base?: I): GetUserActiveSessionsReq {
    return GetUserActiveSessionsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserActiveSessionsReq>, I>>(object: I): GetUserActiveSessionsReq {
    const message = createBaseGetUserActiveSessionsReq();
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseGetUserActiveSessionsResp(): GetUserActiveSessionsResp {
  return { sessions: [] };
}

export const GetUserActiveSessionsResp: MessageFns<GetUserActiveSessionsResp> = {
  encode(message: GetUserActiveSessionsResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sessions) {
      Session.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserActiveSessionsResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserActiveSessionsResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessions.push(Session.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserActiveSessionsResp {
    return {
      sessions: globalThis.Array.isArray(object?.sessions) ? object.sessions.map((e: any) => Session.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetUserActiveSessionsResp): unknown {
    const obj: any = {};
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => Session.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserActiveSessionsResp>, I>>(base?: I): GetUserActiveSessionsResp {
    return GetUserActiveSessionsResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserActiveSessionsResp>, I>>(object: I): GetUserActiveSessionsResp {
    const message = createBaseGetUserActiveSessionsResp();
    message.sessions = object.sessions?.map((e) => Session.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMarkSessionReadReq(): MarkSessionReadReq {
  return { session_id: "", read_seq: "0" };
}

export const MarkSessionReadReq: MessageFns<MarkSessionReadReq> = {
  encode(message: MarkSessionReadReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.read_seq !== "0") {
      writer.uint32(16).uint64(message.read_seq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarkSessionReadReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkSessionReadReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.read_seq = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarkSessionReadReq {
    return {
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      read_seq: isSet(object.readSeq)
        ? globalThis.String(object.readSeq)
        : isSet(object.read_seq)
        ? globalThis.String(object.read_seq)
        : "0",
    };
  },

  toJSON(message: MarkSessionReadReq): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.read_seq !== "0") {
      obj.readSeq = globalThis.String(message.read_seq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarkSessionReadReq>, I>>(base?: I): MarkSessionReadReq {
    return MarkSessionReadReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarkSessionReadReq>, I>>(object: I): MarkSessionReadReq {
    const message = createBaseMarkSessionReadReq();
    message.session_id = object.session_id ?? "";
    message.read_seq = object.read_seq ?? "0";
    return message;
  },
};

function createBaseRecallMessageReq(): RecallMessageReq {
  return { msg_id: "", session_id: "" };
}

export const RecallMessageReq: MessageFns<RecallMessageReq> = {
  encode(message: RecallMessageReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg_id !== "") {
      writer.uint32(10).string(message.msg_id);
    }
    if (message.session_id !== "") {
      writer.uint32(18).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecallMessageReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecallMessageReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecallMessageReq {
    return {
      msg_id: isSet(object.msgId)
        ? globalThis.String(object.msgId)
        : isSet(object.msg_id)
        ? globalThis.String(object.msg_id)
        : "",
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: RecallMessageReq): unknown {
    const obj: any = {};
    if (message.msg_id !== "") {
      obj.msgId = message.msg_id;
    }
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecallMessageReq>, I>>(base?: I): RecallMessageReq {
    return RecallMessageReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecallMessageReq>, I>>(object: I): RecallMessageReq {
    const message = createBaseRecallMessageReq();
    message.msg_id = object.msg_id ?? "";
    message.session_id = object.session_id ?? "";
    return message;
  },
};

function createBaseRecallMessageResp(): RecallMessageResp {
  return {};
}

export const RecallMessageResp: MessageFns<RecallMessageResp> = {
  encode(_: RecallMessageResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecallMessageResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecallMessageResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RecallMessageResp {
    return {};
  },

  toJSON(_: RecallMessageResp): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RecallMessageResp>, I>>(base?: I): RecallMessageResp {
    return RecallMessageResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecallMessageResp>, I>>(_: I): RecallMessageResp {
    const message = createBaseRecallMessageResp();
    return message;
  },
};

function createBaseGetSessionReq(): GetSessionReq {
  return { session_id: "", session_key: "", session_type: 0 };
}

export const GetSessionReq: MessageFns<GetSessionReq> = {
  encode(message: GetSessionReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.session_key !== "") {
      writer.uint32(18).string(message.session_key);
    }
    if (message.session_type !== 0) {
      writer.uint32(24).int32(message.session_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.session_type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionReq {
    return {
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      session_key: isSet(object.sessionKey)
        ? globalThis.String(object.sessionKey)
        : isSet(object.session_key)
        ? globalThis.String(object.session_key)
        : "",
      session_type: isSet(object.sessionType)
        ? globalThis.Number(object.sessionType)
        : isSet(object.session_type)
        ? globalThis.Number(object.session_type)
        : 0,
    };
  },

  toJSON(message: GetSessionReq): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.session_key !== "") {
      obj.sessionKey = message.session_key;
    }
    if (message.session_type !== 0) {
      obj.sessionType = Math.round(message.session_type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSessionReq>, I>>(base?: I): GetSessionReq {
    return GetSessionReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSessionReq>, I>>(object: I): GetSessionReq {
    const message = createBaseGetSessionReq();
    message.session_id = object.session_id ?? "";
    message.session_key = object.session_key ?? "";
    message.session_type = object.session_type ?? 0;
    return message;
  },
};

function createBaseGetSessionResp(): GetSessionResp {
  return { session: undefined };
}

export const GetSessionResp: MessageFns<GetSessionResp> = {
  encode(message: GetSessionResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionResp {
    return { session: isSet(object.session) ? Session.fromJSON(object.session) : undefined };
  },

  toJSON(message: GetSessionResp): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSessionResp>, I>>(base?: I): GetSessionResp {
    return GetSessionResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSessionResp>, I>>(object: I): GetSessionResp {
    const message = createBaseGetSessionResp();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
