// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.31.1
// source: proto/transport/transport.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "transport";

export enum TargetType {
  USER = 0,
  GROUP = 1,
  UNRECOGNIZED = -1,
}

export function targetTypeFromJSON(object: any): TargetType {
  switch (object) {
    case 0:
    case "USER":
      return TargetType.USER;
    case 1:
    case "GROUP":
      return TargetType.GROUP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TargetType.UNRECOGNIZED;
  }
}

export function targetTypeToJSON(object: TargetType): string {
  switch (object) {
    case TargetType.USER:
      return "USER";
    case TargetType.GROUP:
      return "GROUP";
    case TargetType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** WebSocket connection state */
export enum ConnectionState {
  DISCONNECTED = 0,
  CONNECTING = 1,
  CONNECTED = 2,
  RECONNECTING = 3,
  UNRECOGNIZED = -1,
}

export function connectionStateFromJSON(object: any): ConnectionState {
  switch (object) {
    case 0:
    case "DISCONNECTED":
      return ConnectionState.DISCONNECTED;
    case 1:
    case "CONNECTING":
      return ConnectionState.CONNECTING;
    case 2:
    case "CONNECTED":
      return ConnectionState.CONNECTED;
    case 3:
    case "RECONNECTING":
      return ConnectionState.RECONNECTING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConnectionState.UNRECOGNIZED;
  }
}

export function connectionStateToJSON(object: ConnectionState): string {
  switch (object) {
    case ConnectionState.DISCONNECTED:
      return "DISCONNECTED";
    case ConnectionState.CONNECTING:
      return "CONNECTING";
    case ConnectionState.CONNECTED:
      return "CONNECTED";
    case ConnectionState.RECONNECTING:
      return "RECONNECTING";
    case ConnectionState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 消息类型枚举 */
export enum MessageType {
  UNKNOWN = 0,
  /** CHAT_TEXT - 单聊消息 100-199 */
  CHAT_TEXT = 100,
  /** CHAT_IMAGE - 图片消息 */
  CHAT_IMAGE = 101,
  /** CHAT_VIDEO - 视频消息 */
  CHAT_VIDEO = 102,
  /** CHAT_AUDIO - 语音消息 */
  CHAT_AUDIO = 103,
  /** CHAT_FILE - 文件消息 */
  CHAT_FILE = 104,
  /** CHAT_LOCATION - 位置消息 */
  CHAT_LOCATION = 105,
  /** CHAT_CUSTOM - 自定义消息 */
  CHAT_CUSTOM = 106,
  /** GROUP_TEXT - 群聊消息 200-299 */
  GROUP_TEXT = 200,
  /** GROUP_IMAGE - 群图片消息 */
  GROUP_IMAGE = 201,
  /** GROUP_VIDEO - 群视频消息 */
  GROUP_VIDEO = 202,
  /** GROUP_AUDIO - 群语音消息 */
  GROUP_AUDIO = 203,
  /** GROUP_FILE - 群文件消息 */
  GROUP_FILE = 204,
  /** GROUP_NOTICE - 群公告 */
  GROUP_NOTICE = 205,
  /** MSG_ACK - 消息状态 300-399 */
  MSG_ACK = 300,
  /** MSG_READ - 消息已读 */
  MSG_READ = 301,
  /** MSG_DELIVERED - 消息送达 */
  MSG_DELIVERED = 302,
  /** MSG_RECALL - 消息撤回 */
  MSG_RECALL = 303,
  /** MSG_DELETE - 消息删除 */
  MSG_DELETE = 304,
  /** MSG_PERSIST_ACK - 消息持久化确认 */
  MSG_PERSIST_ACK = 305,
  /** USER_ONLINE - 用户状态 400-499 */
  USER_ONLINE = 400,
  /** USER_OFFLINE - 用户下线 */
  USER_OFFLINE = 401,
  /** USER_TYPING - 正在输入 */
  USER_TYPING = 402,
  /** USER_STATUS_CHANGE - 状态变更 */
  USER_STATUS_CHANGE = 403,
  /** USER_KICKOFF - 用户被踢 */
  USER_KICKOFF = 404,
  /** GROUP_OP_NOTIFICATION - 群组操作 */
  GROUP_OP_NOTIFICATION = 500,
  /** MSG_OP_RECALL - 消息操作 */
  MSG_OP_RECALL = 501,
  /** NOTIFICATION - 通知类 600-699 */
  NOTIFICATION = 600,
  /** FRIEND_REQUEST - 好友请求 */
  FRIEND_REQUEST = 601,
  /** FRIEND_ADD - 添加好友 */
  FRIEND_ADD = 602,
  /** FRIEND_DELETED - 删除好友 */
  FRIEND_DELETED = 603,
  /** GROUP_REQUEST - 群请求 */
  GROUP_REQUEST = 604,
  /** UPDATE_SESSION - 内部消费消息 */
  UPDATE_SESSION = 700,
  /** USER_GROUP_SYNC - 用户群组映射同步 */
  USER_GROUP_SYNC = 701,
  /** ERROR - 错误响应 900-999 */
  ERROR = 900,
  UNRECOGNIZED = -1,
}

export function messageTypeFromJSON(object: any): MessageType {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return MessageType.UNKNOWN;
    case 100:
    case "CHAT_TEXT":
      return MessageType.CHAT_TEXT;
    case 101:
    case "CHAT_IMAGE":
      return MessageType.CHAT_IMAGE;
    case 102:
    case "CHAT_VIDEO":
      return MessageType.CHAT_VIDEO;
    case 103:
    case "CHAT_AUDIO":
      return MessageType.CHAT_AUDIO;
    case 104:
    case "CHAT_FILE":
      return MessageType.CHAT_FILE;
    case 105:
    case "CHAT_LOCATION":
      return MessageType.CHAT_LOCATION;
    case 106:
    case "CHAT_CUSTOM":
      return MessageType.CHAT_CUSTOM;
    case 200:
    case "GROUP_TEXT":
      return MessageType.GROUP_TEXT;
    case 201:
    case "GROUP_IMAGE":
      return MessageType.GROUP_IMAGE;
    case 202:
    case "GROUP_VIDEO":
      return MessageType.GROUP_VIDEO;
    case 203:
    case "GROUP_AUDIO":
      return MessageType.GROUP_AUDIO;
    case 204:
    case "GROUP_FILE":
      return MessageType.GROUP_FILE;
    case 205:
    case "GROUP_NOTICE":
      return MessageType.GROUP_NOTICE;
    case 300:
    case "MSG_ACK":
      return MessageType.MSG_ACK;
    case 301:
    case "MSG_READ":
      return MessageType.MSG_READ;
    case 302:
    case "MSG_DELIVERED":
      return MessageType.MSG_DELIVERED;
    case 303:
    case "MSG_RECALL":
      return MessageType.MSG_RECALL;
    case 304:
    case "MSG_DELETE":
      return MessageType.MSG_DELETE;
    case 305:
    case "MSG_PERSIST_ACK":
      return MessageType.MSG_PERSIST_ACK;
    case 400:
    case "USER_ONLINE":
      return MessageType.USER_ONLINE;
    case 401:
    case "USER_OFFLINE":
      return MessageType.USER_OFFLINE;
    case 402:
    case "USER_TYPING":
      return MessageType.USER_TYPING;
    case 403:
    case "USER_STATUS_CHANGE":
      return MessageType.USER_STATUS_CHANGE;
    case 404:
    case "USER_KICKOFF":
      return MessageType.USER_KICKOFF;
    case 500:
    case "GROUP_OP_NOTIFICATION":
      return MessageType.GROUP_OP_NOTIFICATION;
    case 501:
    case "MSG_OP_RECALL":
      return MessageType.MSG_OP_RECALL;
    case 600:
    case "NOTIFICATION":
      return MessageType.NOTIFICATION;
    case 601:
    case "FRIEND_REQUEST":
      return MessageType.FRIEND_REQUEST;
    case 602:
    case "FRIEND_ADD":
      return MessageType.FRIEND_ADD;
    case 603:
    case "FRIEND_DELETED":
      return MessageType.FRIEND_DELETED;
    case 604:
    case "GROUP_REQUEST":
      return MessageType.GROUP_REQUEST;
    case 700:
    case "UPDATE_SESSION":
      return MessageType.UPDATE_SESSION;
    case 701:
    case "USER_GROUP_SYNC":
      return MessageType.USER_GROUP_SYNC;
    case 900:
    case "ERROR":
      return MessageType.ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageType.UNRECOGNIZED;
  }
}

export function messageTypeToJSON(object: MessageType): string {
  switch (object) {
    case MessageType.UNKNOWN:
      return "UNKNOWN";
    case MessageType.CHAT_TEXT:
      return "CHAT_TEXT";
    case MessageType.CHAT_IMAGE:
      return "CHAT_IMAGE";
    case MessageType.CHAT_VIDEO:
      return "CHAT_VIDEO";
    case MessageType.CHAT_AUDIO:
      return "CHAT_AUDIO";
    case MessageType.CHAT_FILE:
      return "CHAT_FILE";
    case MessageType.CHAT_LOCATION:
      return "CHAT_LOCATION";
    case MessageType.CHAT_CUSTOM:
      return "CHAT_CUSTOM";
    case MessageType.GROUP_TEXT:
      return "GROUP_TEXT";
    case MessageType.GROUP_IMAGE:
      return "GROUP_IMAGE";
    case MessageType.GROUP_VIDEO:
      return "GROUP_VIDEO";
    case MessageType.GROUP_AUDIO:
      return "GROUP_AUDIO";
    case MessageType.GROUP_FILE:
      return "GROUP_FILE";
    case MessageType.GROUP_NOTICE:
      return "GROUP_NOTICE";
    case MessageType.MSG_ACK:
      return "MSG_ACK";
    case MessageType.MSG_READ:
      return "MSG_READ";
    case MessageType.MSG_DELIVERED:
      return "MSG_DELIVERED";
    case MessageType.MSG_RECALL:
      return "MSG_RECALL";
    case MessageType.MSG_DELETE:
      return "MSG_DELETE";
    case MessageType.MSG_PERSIST_ACK:
      return "MSG_PERSIST_ACK";
    case MessageType.USER_ONLINE:
      return "USER_ONLINE";
    case MessageType.USER_OFFLINE:
      return "USER_OFFLINE";
    case MessageType.USER_TYPING:
      return "USER_TYPING";
    case MessageType.USER_STATUS_CHANGE:
      return "USER_STATUS_CHANGE";
    case MessageType.USER_KICKOFF:
      return "USER_KICKOFF";
    case MessageType.GROUP_OP_NOTIFICATION:
      return "GROUP_OP_NOTIFICATION";
    case MessageType.MSG_OP_RECALL:
      return "MSG_OP_RECALL";
    case MessageType.NOTIFICATION:
      return "NOTIFICATION";
    case MessageType.FRIEND_REQUEST:
      return "FRIEND_REQUEST";
    case MessageType.FRIEND_ADD:
      return "FRIEND_ADD";
    case MessageType.FRIEND_DELETED:
      return "FRIEND_DELETED";
    case MessageType.GROUP_REQUEST:
      return "GROUP_REQUEST";
    case MessageType.UPDATE_SESSION:
      return "UPDATE_SESSION";
    case MessageType.USER_GROUP_SYNC:
      return "USER_GROUP_SYNC";
    case MessageType.ERROR:
      return "ERROR";
    case MessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 常见错误码定义 */
export enum ErrorCode {
  OK = 0,
  /** INVALID_PARAM - 参数无效 */
  INVALID_PARAM = 1001,
  /** UNAUTHORIZED - 未授权 */
  UNAUTHORIZED = 1002,
  /** TOKEN_EXPIRED - Token过期 */
  TOKEN_EXPIRED = 1003,
  /** USER_NOT_FOUND - 用户不存在 */
  USER_NOT_FOUND = 1004,
  /** MESSAGE_TOO_LARGE - 消息过大 */
  MESSAGE_TOO_LARGE = 1005,
  /** RATE_LIMIT - 频率限制 */
  RATE_LIMIT = 1006,
  /** SERVER_ERROR - 服务器错误 */
  SERVER_ERROR = 5000,
  /** SERVICE_UNAVAILABLE - 服务不可用 */
  SERVICE_UNAVAILABLE = 5001,
  UNRECOGNIZED = -1,
}

export function errorCodeFromJSON(object: any): ErrorCode {
  switch (object) {
    case 0:
    case "OK":
      return ErrorCode.OK;
    case 1001:
    case "INVALID_PARAM":
      return ErrorCode.INVALID_PARAM;
    case 1002:
    case "UNAUTHORIZED":
      return ErrorCode.UNAUTHORIZED;
    case 1003:
    case "TOKEN_EXPIRED":
      return ErrorCode.TOKEN_EXPIRED;
    case 1004:
    case "USER_NOT_FOUND":
      return ErrorCode.USER_NOT_FOUND;
    case 1005:
    case "MESSAGE_TOO_LARGE":
      return ErrorCode.MESSAGE_TOO_LARGE;
    case 1006:
    case "RATE_LIMIT":
      return ErrorCode.RATE_LIMIT;
    case 5000:
    case "SERVER_ERROR":
      return ErrorCode.SERVER_ERROR;
    case 5001:
    case "SERVICE_UNAVAILABLE":
      return ErrorCode.SERVICE_UNAVAILABLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErrorCode.UNRECOGNIZED;
  }
}

export function errorCodeToJSON(object: ErrorCode): string {
  switch (object) {
    case ErrorCode.OK:
      return "OK";
    case ErrorCode.INVALID_PARAM:
      return "INVALID_PARAM";
    case ErrorCode.UNAUTHORIZED:
      return "UNAUTHORIZED";
    case ErrorCode.TOKEN_EXPIRED:
      return "TOKEN_EXPIRED";
    case ErrorCode.USER_NOT_FOUND:
      return "USER_NOT_FOUND";
    case ErrorCode.MESSAGE_TOO_LARGE:
      return "MESSAGE_TOO_LARGE";
    case ErrorCode.RATE_LIMIT:
      return "RATE_LIMIT";
    case ErrorCode.SERVER_ERROR:
      return "SERVER_ERROR";
    case ErrorCode.SERVICE_UNAVAILABLE:
      return "SERVICE_UNAVAILABLE";
    case ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 只保留路由信息，不 import 任何业务结构 */
export interface WSMessage {
  route_target: number[];
  route_target_type: TargetType;
  timestamp: number;
  type: MessageType;
  /** 具体内容各业务包自己解析 */
  payload: Uint8Array;
  sender_id: number;
  version: number;
}

/** API 通用响应包装 */
export interface ApiResponse {
  /** 状态码 (0表示成功) */
  code: number;
  /** 响应提示信息 */
  message: string;
  /** 响应数据(序列化后的pb字节流) */
  data: Uint8Array;
}

/** 错误响应 */
export interface ErrorMessage {
  /** 错误码 */
  error_code: number;
  /** 错误信息 */
  error_msg: string;
  /** 关联会话ID */
  session_id: string;
  /** 关联的请求ID */
  request_id: string;
  /** 错误详情 */
  details: { [key: string]: string };
}

export interface ErrorMessage_DetailsEntry {
  key: string;
  value: string;
}

function createBaseWSMessage(): WSMessage {
  return {
    route_target: [],
    route_target_type: 0,
    timestamp: 0,
    type: 0,
    payload: new Uint8Array(0),
    sender_id: 0,
    version: 0,
  };
}

export const WSMessage: MessageFns<WSMessage> = {
  encode(message: WSMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.route_target) {
      writer.uint64(v);
    }
    writer.join();
    if (message.route_target_type !== 0) {
      writer.uint32(16).int32(message.route_target_type);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.payload.length !== 0) {
      writer.uint32(42).bytes(message.payload);
    }
    if (message.sender_id !== 0) {
      writer.uint32(48).uint64(message.sender_id);
    }
    if (message.version !== 0) {
      writer.uint32(56).int32(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WSMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWSMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.route_target.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.route_target.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.route_target_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sender_id = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WSMessage {
    return {
      route_target: globalThis.Array.isArray(object?.routeTarget)
        ? object.routeTarget.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.route_target)
        ? object.route_target.map((e: any) => globalThis.Number(e))
        : [],
      route_target_type: isSet(object.routeTargetType)
        ? targetTypeFromJSON(object.routeTargetType)
        : isSet(object.route_target_type)
        ? targetTypeFromJSON(object.route_target_type)
        : 0,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      type: isSet(object.type) ? messageTypeFromJSON(object.type) : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      sender_id: isSet(object.senderId)
        ? globalThis.Number(object.senderId)
        : isSet(object.sender_id)
        ? globalThis.Number(object.sender_id)
        : 0,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: WSMessage): unknown {
    const obj: any = {};
    if (message.route_target?.length) {
      obj.routeTarget = message.route_target.map((e) => Math.round(e));
    }
    if (message.route_target_type !== 0) {
      obj.routeTargetType = targetTypeToJSON(message.route_target_type);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.type !== 0) {
      obj.type = messageTypeToJSON(message.type);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.sender_id !== 0) {
      obj.senderId = Math.round(message.sender_id);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WSMessage>, I>>(base?: I): WSMessage {
    return WSMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WSMessage>, I>>(object: I): WSMessage {
    const message = createBaseWSMessage();
    message.route_target = object.route_target?.map((e) => e) || [];
    message.route_target_type = object.route_target_type ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.type = object.type ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    message.sender_id = object.sender_id ?? 0;
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseApiResponse(): ApiResponse {
  return { code: 0, message: "", data: new Uint8Array(0) };
}

export const ApiResponse: MessageFns<ApiResponse> = {
  encode(message: ApiResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApiResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApiResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApiResponse {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: ApiResponse): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApiResponse>, I>>(base?: I): ApiResponse {
    return ApiResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApiResponse>, I>>(object: I): ApiResponse {
    const message = createBaseApiResponse();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseErrorMessage(): ErrorMessage {
  return { error_code: 0, error_msg: "", session_id: "", request_id: "", details: {} };
}

export const ErrorMessage: MessageFns<ErrorMessage> = {
  encode(message: ErrorMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error_code !== 0) {
      writer.uint32(8).int32(message.error_code);
    }
    if (message.error_msg !== "") {
      writer.uint32(18).string(message.error_msg);
    }
    if (message.session_id !== "") {
      writer.uint32(26).string(message.session_id);
    }
    if (message.request_id !== "") {
      writer.uint32(34).string(message.request_id);
    }
    globalThis.Object.entries(message.details).forEach(([key, value]: [string, string]) => {
      ErrorMessage_DetailsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error_code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error_msg = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.request_id = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = ErrorMessage_DetailsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.details[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorMessage {
    return {
      error_code: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
      error_msg: isSet(object.errorMsg)
        ? globalThis.String(object.errorMsg)
        : isSet(object.error_msg)
        ? globalThis.String(object.error_msg)
        : "",
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      request_id: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      details: isObject(object.details)
        ? (globalThis.Object.entries(object.details) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ErrorMessage): unknown {
    const obj: any = {};
    if (message.error_code !== 0) {
      obj.errorCode = Math.round(message.error_code);
    }
    if (message.error_msg !== "") {
      obj.errorMsg = message.error_msg;
    }
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    if (message.request_id !== "") {
      obj.requestId = message.request_id;
    }
    if (message.details) {
      const entries = globalThis.Object.entries(message.details) as [string, string][];
      if (entries.length > 0) {
        obj.details = {};
        entries.forEach(([k, v]) => {
          obj.details[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorMessage>, I>>(base?: I): ErrorMessage {
    return ErrorMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorMessage>, I>>(object: I): ErrorMessage {
    const message = createBaseErrorMessage();
    message.error_code = object.error_code ?? 0;
    message.error_msg = object.error_msg ?? "";
    message.session_id = object.session_id ?? "";
    message.request_id = object.request_id ?? "";
    message.details = (globalThis.Object.entries(object.details ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseErrorMessage_DetailsEntry(): ErrorMessage_DetailsEntry {
  return { key: "", value: "" };
}

export const ErrorMessage_DetailsEntry: MessageFns<ErrorMessage_DetailsEntry> = {
  encode(message: ErrorMessage_DetailsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorMessage_DetailsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorMessage_DetailsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorMessage_DetailsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ErrorMessage_DetailsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorMessage_DetailsEntry>, I>>(base?: I): ErrorMessage_DetailsEntry {
    return ErrorMessage_DetailsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorMessage_DetailsEntry>, I>>(object: I): ErrorMessage_DetailsEntry {
    const message = createBaseErrorMessage_DetailsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
