// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.31.1
// source: apis/auth/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types";

/** LoginReq */
export interface LoginReq {
  /** @gotags: json:"account" */
  account: number;
  /** @gotags: json:"password" */
  password: string;
  /** @gotags: json:"device_id" */
  device_id: string;
  /** @gotags: json:"platform" */
  platform: string;
}

/** LoginResp */
export interface LoginResp {
  /** @gotags: json:"token" */
  token: string;
  /** @gotags: json:"refresh_token" */
  refresh_token: string;
}

/** LogoutReq */
export interface LogoutReq {
  /** @gotags: json:"remove_rt" */
  remove_rt: boolean;
  /** @gotags: json:"device_id" */
  device_id: string;
}

/** RegisterReq */
export interface RegisterReq {
  /** @gotags: json:"name" */
  name: string;
  /** @gotags: json:"password" */
  password: string;
  /** @gotags: json:"phone" */
  phone: string;
  /** @gotags: json:"auth_code" */
  auth_code: string;
}

/** RegisterResp */
export interface RegisterResp {
  /** @gotags: json:"id" */
  id: number;
}

/** GetAuthCodeReq */
export interface GetAuthCodeReq {
  /** @gotags: json:"phone" */
  phone: string;
}

/** GetAuthCodeResp */
export interface GetAuthCodeResp {
}

/** RefreshReq */
export interface RefreshReq {
  /** @gotags: json:"device_id" */
  device_id: string;
  /** @gotags: json:"platform" */
  platform: string;
  /** @gotags: json:"refresh_token,omitempty" */
  refresh_token: string;
}

/** RefreshResp */
export interface RefreshResp {
  /** @gotags: json:"token" */
  token: string;
  /** @gotags: json:"refresh_token" */
  refresh_token: string;
}

function createBaseLoginReq(): LoginReq {
  return { account: 0, password: "", device_id: "", platform: "" };
}

export const LoginReq: MessageFns<LoginReq> = {
  encode(message: LoginReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== 0) {
      writer.uint32(8).int64(message.account);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.device_id !== "") {
      writer.uint32(26).string(message.device_id);
    }
    if (message.platform !== "") {
      writer.uint32(34).string(message.platform);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.account = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.device_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginReq {
    return {
      account: isSet(object.account) ? globalThis.Number(object.account) : 0,
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      device_id: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
    };
  },

  toJSON(message: LoginReq): unknown {
    const obj: any = {};
    if (message.account !== 0) {
      obj.account = Math.round(message.account);
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.device_id !== "") {
      obj.deviceId = message.device_id;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginReq>, I>>(base?: I): LoginReq {
    return LoginReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginReq>, I>>(object: I): LoginReq {
    const message = createBaseLoginReq();
    message.account = object.account ?? 0;
    message.password = object.password ?? "";
    message.device_id = object.device_id ?? "";
    message.platform = object.platform ?? "";
    return message;
  },
};

function createBaseLoginResp(): LoginResp {
  return { token: "", refresh_token: "" };
}

export const LoginResp: MessageFns<LoginResp> = {
  encode(message: LoginResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.refresh_token !== "") {
      writer.uint32(18).string(message.refresh_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refresh_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResp {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      refresh_token: isSet(object.refreshToken)
        ? globalThis.String(object.refreshToken)
        : isSet(object.refresh_token)
        ? globalThis.String(object.refresh_token)
        : "",
    };
  },

  toJSON(message: LoginResp): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.refresh_token !== "") {
      obj.refreshToken = message.refresh_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResp>, I>>(base?: I): LoginResp {
    return LoginResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResp>, I>>(object: I): LoginResp {
    const message = createBaseLoginResp();
    message.token = object.token ?? "";
    message.refresh_token = object.refresh_token ?? "";
    return message;
  },
};

function createBaseLogoutReq(): LogoutReq {
  return { remove_rt: false, device_id: "" };
}

export const LogoutReq: MessageFns<LogoutReq> = {
  encode(message: LogoutReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.remove_rt !== false) {
      writer.uint32(8).bool(message.remove_rt);
    }
    if (message.device_id !== "") {
      writer.uint32(18).string(message.device_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.remove_rt = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.device_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutReq {
    return {
      remove_rt: isSet(object.removeRt)
        ? globalThis.Boolean(object.removeRt)
        : isSet(object.remove_rt)
        ? globalThis.Boolean(object.remove_rt)
        : false,
      device_id: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
    };
  },

  toJSON(message: LogoutReq): unknown {
    const obj: any = {};
    if (message.remove_rt !== false) {
      obj.removeRt = message.remove_rt;
    }
    if (message.device_id !== "") {
      obj.deviceId = message.device_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutReq>, I>>(base?: I): LogoutReq {
    return LogoutReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutReq>, I>>(object: I): LogoutReq {
    const message = createBaseLogoutReq();
    message.remove_rt = object.remove_rt ?? false;
    message.device_id = object.device_id ?? "";
    return message;
  },
};

function createBaseRegisterReq(): RegisterReq {
  return { name: "", password: "", phone: "", auth_code: "" };
}

export const RegisterReq: MessageFns<RegisterReq> = {
  encode(message: RegisterReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.phone !== "") {
      writer.uint32(26).string(message.phone);
    }
    if (message.auth_code !== "") {
      writer.uint32(34).string(message.auth_code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.auth_code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterReq {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      auth_code: isSet(object.authCode)
        ? globalThis.String(object.authCode)
        : isSet(object.auth_code)
        ? globalThis.String(object.auth_code)
        : "",
    };
  },

  toJSON(message: RegisterReq): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.auth_code !== "") {
      obj.authCode = message.auth_code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterReq>, I>>(base?: I): RegisterReq {
    return RegisterReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterReq>, I>>(object: I): RegisterReq {
    const message = createBaseRegisterReq();
    message.name = object.name ?? "";
    message.password = object.password ?? "";
    message.phone = object.phone ?? "";
    message.auth_code = object.auth_code ?? "";
    return message;
  },
};

function createBaseRegisterResp(): RegisterResp {
  return { id: 0 };
}

export const RegisterResp: MessageFns<RegisterResp> = {
  encode(message: RegisterResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterResp {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: RegisterResp): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterResp>, I>>(base?: I): RegisterResp {
    return RegisterResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterResp>, I>>(object: I): RegisterResp {
    const message = createBaseRegisterResp();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGetAuthCodeReq(): GetAuthCodeReq {
  return { phone: "" };
}

export const GetAuthCodeReq: MessageFns<GetAuthCodeReq> = {
  encode(message: GetAuthCodeReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phone !== "") {
      writer.uint32(10).string(message.phone);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAuthCodeReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAuthCodeReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAuthCodeReq {
    return { phone: isSet(object.phone) ? globalThis.String(object.phone) : "" };
  },

  toJSON(message: GetAuthCodeReq): unknown {
    const obj: any = {};
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAuthCodeReq>, I>>(base?: I): GetAuthCodeReq {
    return GetAuthCodeReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAuthCodeReq>, I>>(object: I): GetAuthCodeReq {
    const message = createBaseGetAuthCodeReq();
    message.phone = object.phone ?? "";
    return message;
  },
};

function createBaseGetAuthCodeResp(): GetAuthCodeResp {
  return {};
}

export const GetAuthCodeResp: MessageFns<GetAuthCodeResp> = {
  encode(_: GetAuthCodeResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAuthCodeResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAuthCodeResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetAuthCodeResp {
    return {};
  },

  toJSON(_: GetAuthCodeResp): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAuthCodeResp>, I>>(base?: I): GetAuthCodeResp {
    return GetAuthCodeResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAuthCodeResp>, I>>(_: I): GetAuthCodeResp {
    const message = createBaseGetAuthCodeResp();
    return message;
  },
};

function createBaseRefreshReq(): RefreshReq {
  return { device_id: "", platform: "", refresh_token: "" };
}

export const RefreshReq: MessageFns<RefreshReq> = {
  encode(message: RefreshReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.device_id !== "") {
      writer.uint32(10).string(message.device_id);
    }
    if (message.platform !== "") {
      writer.uint32(18).string(message.platform);
    }
    if (message.refresh_token !== "") {
      writer.uint32(26).string(message.refresh_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.device_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.refresh_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshReq {
    return {
      device_id: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      refresh_token: isSet(object.refreshToken)
        ? globalThis.String(object.refreshToken)
        : isSet(object.refresh_token)
        ? globalThis.String(object.refresh_token)
        : "",
    };
  },

  toJSON(message: RefreshReq): unknown {
    const obj: any = {};
    if (message.device_id !== "") {
      obj.deviceId = message.device_id;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.refresh_token !== "") {
      obj.refreshToken = message.refresh_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshReq>, I>>(base?: I): RefreshReq {
    return RefreshReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshReq>, I>>(object: I): RefreshReq {
    const message = createBaseRefreshReq();
    message.device_id = object.device_id ?? "";
    message.platform = object.platform ?? "";
    message.refresh_token = object.refresh_token ?? "";
    return message;
  },
};

function createBaseRefreshResp(): RefreshResp {
  return { token: "", refresh_token: "" };
}

export const RefreshResp: MessageFns<RefreshResp> = {
  encode(message: RefreshResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.refresh_token !== "") {
      writer.uint32(18).string(message.refresh_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refresh_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshResp {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      refresh_token: isSet(object.refreshToken)
        ? globalThis.String(object.refreshToken)
        : isSet(object.refresh_token)
        ? globalThis.String(object.refresh_token)
        : "",
    };
  },

  toJSON(message: RefreshResp): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.refresh_token !== "") {
      obj.refreshToken = message.refresh_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshResp>, I>>(base?: I): RefreshResp {
    return RefreshResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshResp>, I>>(object: I): RefreshResp {
    const message = createBaseRefreshResp();
    message.token = object.token ?? "";
    message.refresh_token = object.refresh_token ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
