// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v7.34.0
// source: apis/file/file.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types";

export enum FileType {
  FileTypeAvatar = 0,
  FileTypeChatImage = 1,
  FileTypeChatFile = 2,
  UNRECOGNIZED = -1,
}

export function fileTypeFromJSON(object: any): FileType {
  switch (object) {
    case 0:
    case "FileTypeAvatar":
      return FileType.FileTypeAvatar;
    case 1:
    case "FileTypeChatImage":
      return FileType.FileTypeChatImage;
    case 2:
    case "FileTypeChatFile":
      return FileType.FileTypeChatFile;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FileType.UNRECOGNIZED;
  }
}

export function fileTypeToJSON(object: FileType): string {
  switch (object) {
    case FileType.FileTypeAvatar:
      return "FileTypeAvatar";
    case FileType.FileTypeChatImage:
      return "FileTypeChatImage";
    case FileType.FileTypeChatFile:
      return "FileTypeChatFile";
    case FileType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface PolicyToken {
  /** @gotags: json:"policy" */
  policy: string;
  /** @gotags: json:"security_token" */
  security_token: string;
  /** @gotags: json:"x_oss_signature_version" */
  x_oss_signature_version: string;
  /** @gotags: json:"x_oss_credential" */
  x_oss_credential: string;
  /** @gotags: json:"x_oss_date" */
  x_oss_date: string;
  /** @gotags: json:"signature" */
  signature: string;
  /** @gotags: json:"host" */
  host: string;
  /** @gotags: json:"dir" */
  dir: string;
  /** @gotags: json:"callback" */
  callback: string;
}

export interface CallbackParam {
  /** @gotags: json:"callbackUrl" */
  callbackUrl: string;
  /** @gotags: json:"callbackBody" */
  callbackBody: string;
  /** @gotags: json:"callbackBodyType" */
  callbackBodyType: string;
}

export interface CallbackData {
  /** @gotags: form:"id,optional" json:"id,optional" */
  id: number;
  /** @gotags: form:"file_type,optional" json:"file_type,optional" */
  file_type: number;
  /** @gotags: form:"width,optional" json:"width,optional" */
  width: number;
  /** @gotags: form:"height,optional" json:"height,optional" */
  height: number;
  /** @gotags: form:"size,optional" json:"size,optional" */
  size: number;
  /** @gotags: form:"file_name,optional" json:"file_name,optional" */
  file_name: string;
  /** @gotags: form:"mime_type,optional" json:"mime_type,optional" */
  mime_type: string;
}

export interface GetPostSignatureReq {
  /** @gotags: form:"file_type,optional" json:"file_type,optional" */
  file_type: number;
}

export interface GetAccessUrlReq {
  /** @gotags: form:"file_key,optional" json:"file_key,optional" */
  file_key: string;
  /** @gotags: form:"file_type,optional" json:"file_type,optional" */
  file_type: FileType;
  /** @gotags: form:"oss_process,optional" json:"oss_process,optional" */
  oss_process: string;
}

export interface GetAccessUrlResp {
  /** @gotags: json:"access_url" */
  access_url: string;
}

function createBasePolicyToken(): PolicyToken {
  return {
    policy: "",
    security_token: "",
    x_oss_signature_version: "",
    x_oss_credential: "",
    x_oss_date: "",
    signature: "",
    host: "",
    dir: "",
    callback: "",
  };
}

export const PolicyToken: MessageFns<PolicyToken> = {
  encode(message: PolicyToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.policy !== "") {
      writer.uint32(10).string(message.policy);
    }
    if (message.security_token !== "") {
      writer.uint32(18).string(message.security_token);
    }
    if (message.x_oss_signature_version !== "") {
      writer.uint32(26).string(message.x_oss_signature_version);
    }
    if (message.x_oss_credential !== "") {
      writer.uint32(34).string(message.x_oss_credential);
    }
    if (message.x_oss_date !== "") {
      writer.uint32(42).string(message.x_oss_date);
    }
    if (message.signature !== "") {
      writer.uint32(50).string(message.signature);
    }
    if (message.host !== "") {
      writer.uint32(58).string(message.host);
    }
    if (message.dir !== "") {
      writer.uint32(66).string(message.dir);
    }
    if (message.callback !== "") {
      writer.uint32(74).string(message.callback);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PolicyToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePolicyToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.policy = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.security_token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.x_oss_signature_version = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.x_oss_credential = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.x_oss_date = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.dir = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.callback = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PolicyToken {
    return {
      policy: isSet(object.policy) ? globalThis.String(object.policy) : "",
      security_token: isSet(object.securityToken)
        ? globalThis.String(object.securityToken)
        : isSet(object.security_token)
        ? globalThis.String(object.security_token)
        : "",
      x_oss_signature_version: isSet(object.xOssSignatureVersion)
        ? globalThis.String(object.xOssSignatureVersion)
        : isSet(object.x_oss_signature_version)
        ? globalThis.String(object.x_oss_signature_version)
        : "",
      x_oss_credential: isSet(object.xOssCredential)
        ? globalThis.String(object.xOssCredential)
        : isSet(object.x_oss_credential)
        ? globalThis.String(object.x_oss_credential)
        : "",
      x_oss_date: isSet(object.xOssDate)
        ? globalThis.String(object.xOssDate)
        : isSet(object.x_oss_date)
        ? globalThis.String(object.x_oss_date)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      dir: isSet(object.dir) ? globalThis.String(object.dir) : "",
      callback: isSet(object.callback) ? globalThis.String(object.callback) : "",
    };
  },

  toJSON(message: PolicyToken): unknown {
    const obj: any = {};
    if (message.policy !== "") {
      obj.policy = message.policy;
    }
    if (message.security_token !== "") {
      obj.securityToken = message.security_token;
    }
    if (message.x_oss_signature_version !== "") {
      obj.xOssSignatureVersion = message.x_oss_signature_version;
    }
    if (message.x_oss_credential !== "") {
      obj.xOssCredential = message.x_oss_credential;
    }
    if (message.x_oss_date !== "") {
      obj.xOssDate = message.x_oss_date;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.dir !== "") {
      obj.dir = message.dir;
    }
    if (message.callback !== "") {
      obj.callback = message.callback;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PolicyToken>, I>>(base?: I): PolicyToken {
    return PolicyToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PolicyToken>, I>>(object: I): PolicyToken {
    const message = createBasePolicyToken();
    message.policy = object.policy ?? "";
    message.security_token = object.security_token ?? "";
    message.x_oss_signature_version = object.x_oss_signature_version ?? "";
    message.x_oss_credential = object.x_oss_credential ?? "";
    message.x_oss_date = object.x_oss_date ?? "";
    message.signature = object.signature ?? "";
    message.host = object.host ?? "";
    message.dir = object.dir ?? "";
    message.callback = object.callback ?? "";
    return message;
  },
};

function createBaseCallbackParam(): CallbackParam {
  return { callbackUrl: "", callbackBody: "", callbackBodyType: "" };
}

export const CallbackParam: MessageFns<CallbackParam> = {
  encode(message: CallbackParam, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callbackUrl !== "") {
      writer.uint32(10).string(message.callbackUrl);
    }
    if (message.callbackBody !== "") {
      writer.uint32(18).string(message.callbackBody);
    }
    if (message.callbackBodyType !== "") {
      writer.uint32(26).string(message.callbackBodyType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallbackParam {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallbackParam();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callbackUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.callbackBody = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.callbackBodyType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallbackParam {
    return {
      callbackUrl: isSet(object.callbackUrl) ? globalThis.String(object.callbackUrl) : "",
      callbackBody: isSet(object.callbackBody) ? globalThis.String(object.callbackBody) : "",
      callbackBodyType: isSet(object.callbackBodyType) ? globalThis.String(object.callbackBodyType) : "",
    };
  },

  toJSON(message: CallbackParam): unknown {
    const obj: any = {};
    if (message.callbackUrl !== "") {
      obj.callbackUrl = message.callbackUrl;
    }
    if (message.callbackBody !== "") {
      obj.callbackBody = message.callbackBody;
    }
    if (message.callbackBodyType !== "") {
      obj.callbackBodyType = message.callbackBodyType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallbackParam>, I>>(base?: I): CallbackParam {
    return CallbackParam.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallbackParam>, I>>(object: I): CallbackParam {
    const message = createBaseCallbackParam();
    message.callbackUrl = object.callbackUrl ?? "";
    message.callbackBody = object.callbackBody ?? "";
    message.callbackBodyType = object.callbackBodyType ?? "";
    return message;
  },
};

function createBaseCallbackData(): CallbackData {
  return { id: 0, file_type: 0, width: 0, height: 0, size: 0, file_name: "", mime_type: "" };
}

export const CallbackData: MessageFns<CallbackData> = {
  encode(message: CallbackData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.file_type !== 0) {
      writer.uint32(16).int32(message.file_type);
    }
    if (message.width !== 0) {
      writer.uint32(24).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(32).int32(message.height);
    }
    if (message.size !== 0) {
      writer.uint32(40).uint64(message.size);
    }
    if (message.file_name !== "") {
      writer.uint32(50).string(message.file_name);
    }
    if (message.mime_type !== "") {
      writer.uint32(58).string(message.mime_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallbackData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallbackData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.file_type = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.size = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.mime_type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallbackData {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      file_type: isSet(object.fileType)
        ? globalThis.Number(object.fileType)
        : isSet(object.file_type)
        ? globalThis.Number(object.file_type)
        : 0,
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      file_name: isSet(object.fileName)
        ? globalThis.String(object.fileName)
        : isSet(object.file_name)
        ? globalThis.String(object.file_name)
        : "",
      mime_type: isSet(object.mimeType)
        ? globalThis.String(object.mimeType)
        : isSet(object.mime_type)
        ? globalThis.String(object.mime_type)
        : "",
    };
  },

  toJSON(message: CallbackData): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.file_type !== 0) {
      obj.fileType = Math.round(message.file_type);
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.file_name !== "") {
      obj.fileName = message.file_name;
    }
    if (message.mime_type !== "") {
      obj.mimeType = message.mime_type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallbackData>, I>>(base?: I): CallbackData {
    return CallbackData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallbackData>, I>>(object: I): CallbackData {
    const message = createBaseCallbackData();
    message.id = object.id ?? 0;
    message.file_type = object.file_type ?? 0;
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.size = object.size ?? 0;
    message.file_name = object.file_name ?? "";
    message.mime_type = object.mime_type ?? "";
    return message;
  },
};

function createBaseGetPostSignatureReq(): GetPostSignatureReq {
  return { file_type: 0 };
}

export const GetPostSignatureReq: MessageFns<GetPostSignatureReq> = {
  encode(message: GetPostSignatureReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_type !== 0) {
      writer.uint32(8).int32(message.file_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPostSignatureReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPostSignatureReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.file_type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPostSignatureReq {
    return {
      file_type: isSet(object.fileType)
        ? globalThis.Number(object.fileType)
        : isSet(object.file_type)
        ? globalThis.Number(object.file_type)
        : 0,
    };
  },

  toJSON(message: GetPostSignatureReq): unknown {
    const obj: any = {};
    if (message.file_type !== 0) {
      obj.fileType = Math.round(message.file_type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPostSignatureReq>, I>>(base?: I): GetPostSignatureReq {
    return GetPostSignatureReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPostSignatureReq>, I>>(object: I): GetPostSignatureReq {
    const message = createBaseGetPostSignatureReq();
    message.file_type = object.file_type ?? 0;
    return message;
  },
};

function createBaseGetAccessUrlReq(): GetAccessUrlReq {
  return { file_key: "", file_type: 0, oss_process: "" };
}

export const GetAccessUrlReq: MessageFns<GetAccessUrlReq> = {
  encode(message: GetAccessUrlReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_key !== "") {
      writer.uint32(10).string(message.file_key);
    }
    if (message.file_type !== 0) {
      writer.uint32(16).int32(message.file_type);
    }
    if (message.oss_process !== "") {
      writer.uint32(26).string(message.oss_process);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccessUrlReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccessUrlReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.oss_process = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccessUrlReq {
    return {
      file_key: isSet(object.fileKey)
        ? globalThis.String(object.fileKey)
        : isSet(object.file_key)
        ? globalThis.String(object.file_key)
        : "",
      file_type: isSet(object.fileType)
        ? fileTypeFromJSON(object.fileType)
        : isSet(object.file_type)
        ? fileTypeFromJSON(object.file_type)
        : 0,
      oss_process: isSet(object.ossProcess)
        ? globalThis.String(object.ossProcess)
        : isSet(object.oss_process)
        ? globalThis.String(object.oss_process)
        : "",
    };
  },

  toJSON(message: GetAccessUrlReq): unknown {
    const obj: any = {};
    if (message.file_key !== "") {
      obj.fileKey = message.file_key;
    }
    if (message.file_type !== 0) {
      obj.fileType = fileTypeToJSON(message.file_type);
    }
    if (message.oss_process !== "") {
      obj.ossProcess = message.oss_process;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccessUrlReq>, I>>(base?: I): GetAccessUrlReq {
    return GetAccessUrlReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccessUrlReq>, I>>(object: I): GetAccessUrlReq {
    const message = createBaseGetAccessUrlReq();
    message.file_key = object.file_key ?? "";
    message.file_type = object.file_type ?? 0;
    message.oss_process = object.oss_process ?? "";
    return message;
  },
};

function createBaseGetAccessUrlResp(): GetAccessUrlResp {
  return { access_url: "" };
}

export const GetAccessUrlResp: MessageFns<GetAccessUrlResp> = {
  encode(message: GetAccessUrlResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.access_url !== "") {
      writer.uint32(10).string(message.access_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccessUrlResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccessUrlResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccessUrlResp {
    return {
      access_url: isSet(object.accessUrl)
        ? globalThis.String(object.accessUrl)
        : isSet(object.access_url)
        ? globalThis.String(object.access_url)
        : "",
    };
  },

  toJSON(message: GetAccessUrlResp): unknown {
    const obj: any = {};
    if (message.access_url !== "") {
      obj.accessUrl = message.access_url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccessUrlResp>, I>>(base?: I): GetAccessUrlResp {
    return GetAccessUrlResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccessUrlResp>, I>>(object: I): GetAccessUrlResp {
    const message = createBaseGetAccessUrlResp();
    message.access_url = object.access_url ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
