// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v7.34.0
// source: apis/message/message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types";

/** Message */
export interface Message {
  /** @gotags: json:"msg_id" */
  msg_id: string;
  /** @gotags: json:"client_id" */
  client_id: string;
  /** @gotags: json:"conversation_id" */
  conversation_id: string;
  /** @gotags: json:"from_user_id" */
  from_user_id: number;
  /** @gotags: json:"msg_type" */
  msg_type: number;
  /** @gotags: json:"seq" */
  seq: number;
  /** @gotags: json:"content" */
  content: string;
  /** @gotags: json:"media_url" */
  media_url: string;
  /** @gotags: json:"extra" */
  extra: string;
  /** @gotags: json:"status" */
  status: number;
  /** @gotags: json:"create_time" */
  create_time: number;
}

export interface Conversation {
  conversation_id: string;
  conversation_type: number;
  max_seq: number;
  create_time: number;
  update_time: number;
  last_content: string;
  last_sender: number;
}

/** UserConversation */
export interface UserConversation {
  /** @gotags: json:"user_id" */
  user_id: number;
  /** @gotags: json:"conversation_id" */
  conversation_id: string;
  /** @gotags: json:"is_top" */
  is_top: boolean;
  /** @gotags: json:"is_disturb" */
  is_disturb: boolean;
  /** @gotags: json:"is_mute" */
  is_mute: boolean;
  /** @gotags: json:"last_read_seq" */
  last_read_seq: number;
  /** @gotags: json:"create_time" */
  create_time: number;
  /** @gotags: json:"update_time" */
  update_time: number;
}

/** GetHistoryReq */
export interface GetHistoryReq {
  /** @gotags: form:"conversation_id,optional" json:"conversation_id,optional" */
  conversation_id: string;
  /** @gotags: form:"start_seq,optional" json:"start_seq,optional" */
  start_seq: number;
  /** @gotags: form:"end_seq,optional" json:"end_seq,optional" */
  end_seq: number;
  /** @gotags: form:"limit,optional,default=20" json:"limit,optional" */
  limit: number;
}

/** GetHistoryResp */
export interface GetHistoryResp {
  /** @gotags: json:"list" */
  list: Message[];
}

/** ReadMessageReq */
export interface ReadMessageReq {
  /** @gotags: json:"conversation_id" */
  conversation_id: string;
  /** @gotags: json:"seq" */
  seq: number;
}

/** UpdateConversationReq */
export interface UpdateConversationReq {
  /** @gotags: json:"conversation_id" */
  conversation_id: string;
  /** @gotags: json:"is_top,optional" */
  is_top: number;
  /** @gotags: json:"is_disturb,optional" */
  is_disturb: number;
  /** @gotags: json:"is_mute,optional" */
  is_mute: number;
}

/** GetUserConversationsResp */
export interface GetUserConversationsResp {
  /** @gotags: json:"conversations" */
  conversations: UserConversation[];
}

export interface GetUserActiveConversationsReq {
  /** @gotags: form:"timestamp,optional" json:"timestamp,optional" */
  timestamp: number;
}

export interface GetUserActiveConversationsResp {
  /** @gotags: json:"conversations" */
  conversations: Conversation[];
}

export interface RecallMessageReq {
  /** @gotags: json:"msg_id" */
  msg_id: string;
  /** @gotags: json:"session_id" */
  session_id: string;
}

function createBaseMessage(): Message {
  return {
    msg_id: "",
    client_id: "",
    conversation_id: "",
    from_user_id: 0,
    msg_type: 0,
    seq: 0,
    content: "",
    media_url: "",
    extra: "",
    status: 0,
    create_time: 0,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg_id !== "") {
      writer.uint32(10).string(message.msg_id);
    }
    if (message.client_id !== "") {
      writer.uint32(18).string(message.client_id);
    }
    if (message.conversation_id !== "") {
      writer.uint32(26).string(message.conversation_id);
    }
    if (message.from_user_id !== 0) {
      writer.uint32(32).uint64(message.from_user_id);
    }
    if (message.msg_type !== 0) {
      writer.uint32(40).int32(message.msg_type);
    }
    if (message.seq !== 0) {
      writer.uint32(48).uint64(message.seq);
    }
    if (message.content !== "") {
      writer.uint32(58).string(message.content);
    }
    if (message.media_url !== "") {
      writer.uint32(66).string(message.media_url);
    }
    if (message.extra !== "") {
      writer.uint32(74).string(message.extra);
    }
    if (message.status !== 0) {
      writer.uint32(80).int32(message.status);
    }
    if (message.create_time !== 0) {
      writer.uint32(88).int64(message.create_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.client_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.from_user_id = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.msg_type = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.media_url = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.extra = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      msg_id: isSet(object.msgId)
        ? globalThis.String(object.msgId)
        : isSet(object.msg_id)
        ? globalThis.String(object.msg_id)
        : "",
      client_id: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      from_user_id: isSet(object.fromUserId)
        ? globalThis.Number(object.fromUserId)
        : isSet(object.from_user_id)
        ? globalThis.Number(object.from_user_id)
        : 0,
      msg_type: isSet(object.msgType)
        ? globalThis.Number(object.msgType)
        : isSet(object.msg_type)
        ? globalThis.Number(object.msg_type)
        : 0,
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      media_url: isSet(object.mediaUrl)
        ? globalThis.String(object.mediaUrl)
        : isSet(object.media_url)
        ? globalThis.String(object.media_url)
        : "",
      extra: isSet(object.extra) ? globalThis.String(object.extra) : "",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.msg_id !== "") {
      obj.msgId = message.msg_id;
    }
    if (message.client_id !== "") {
      obj.clientId = message.client_id;
    }
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.from_user_id !== 0) {
      obj.fromUserId = Math.round(message.from_user_id);
    }
    if (message.msg_type !== 0) {
      obj.msgType = Math.round(message.msg_type);
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.media_url !== "") {
      obj.mediaUrl = message.media_url;
    }
    if (message.extra !== "") {
      obj.extra = message.extra;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.msg_id = object.msg_id ?? "";
    message.client_id = object.client_id ?? "";
    message.conversation_id = object.conversation_id ?? "";
    message.from_user_id = object.from_user_id ?? 0;
    message.msg_type = object.msg_type ?? 0;
    message.seq = object.seq ?? 0;
    message.content = object.content ?? "";
    message.media_url = object.media_url ?? "";
    message.extra = object.extra ?? "";
    message.status = object.status ?? 0;
    message.create_time = object.create_time ?? 0;
    return message;
  },
};

function createBaseConversation(): Conversation {
  return {
    conversation_id: "",
    conversation_type: 0,
    max_seq: 0,
    create_time: 0,
    update_time: 0,
    last_content: "",
    last_sender: 0,
  };
}

export const Conversation: MessageFns<Conversation> = {
  encode(message: Conversation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversation_id !== "") {
      writer.uint32(10).string(message.conversation_id);
    }
    if (message.conversation_type !== 0) {
      writer.uint32(16).int32(message.conversation_type);
    }
    if (message.max_seq !== 0) {
      writer.uint32(24).int64(message.max_seq);
    }
    if (message.create_time !== 0) {
      writer.uint32(32).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(40).int64(message.update_time);
    }
    if (message.last_content !== "") {
      writer.uint32(50).string(message.last_content);
    }
    if (message.last_sender !== 0) {
      writer.uint32(56).uint64(message.last_sender);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Conversation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConversation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.conversation_type = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.max_seq = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.last_content = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.last_sender = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Conversation {
    return {
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      conversation_type: isSet(object.conversationType)
        ? globalThis.Number(object.conversationType)
        : isSet(object.conversation_type)
        ? globalThis.Number(object.conversation_type)
        : 0,
      max_seq: isSet(object.maxSeq)
        ? globalThis.Number(object.maxSeq)
        : isSet(object.max_seq)
        ? globalThis.Number(object.max_seq)
        : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
      last_content: isSet(object.lastContent)
        ? globalThis.String(object.lastContent)
        : isSet(object.last_content)
        ? globalThis.String(object.last_content)
        : "",
      last_sender: isSet(object.lastSender)
        ? globalThis.Number(object.lastSender)
        : isSet(object.last_sender)
        ? globalThis.Number(object.last_sender)
        : 0,
    };
  },

  toJSON(message: Conversation): unknown {
    const obj: any = {};
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.conversation_type !== 0) {
      obj.conversationType = Math.round(message.conversation_type);
    }
    if (message.max_seq !== 0) {
      obj.maxSeq = Math.round(message.max_seq);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    if (message.last_content !== "") {
      obj.lastContent = message.last_content;
    }
    if (message.last_sender !== 0) {
      obj.lastSender = Math.round(message.last_sender);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Conversation>, I>>(base?: I): Conversation {
    return Conversation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Conversation>, I>>(object: I): Conversation {
    const message = createBaseConversation();
    message.conversation_id = object.conversation_id ?? "";
    message.conversation_type = object.conversation_type ?? 0;
    message.max_seq = object.max_seq ?? 0;
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    message.last_content = object.last_content ?? "";
    message.last_sender = object.last_sender ?? 0;
    return message;
  },
};

function createBaseUserConversation(): UserConversation {
  return {
    user_id: 0,
    conversation_id: "",
    is_top: false,
    is_disturb: false,
    is_mute: false,
    last_read_seq: 0,
    create_time: 0,
    update_time: 0,
  };
}

export const UserConversation: MessageFns<UserConversation> = {
  encode(message: UserConversation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== 0) {
      writer.uint32(8).uint64(message.user_id);
    }
    if (message.conversation_id !== "") {
      writer.uint32(18).string(message.conversation_id);
    }
    if (message.is_top !== false) {
      writer.uint32(24).bool(message.is_top);
    }
    if (message.is_disturb !== false) {
      writer.uint32(32).bool(message.is_disturb);
    }
    if (message.is_mute !== false) {
      writer.uint32(40).bool(message.is_mute);
    }
    if (message.last_read_seq !== 0) {
      writer.uint32(48).uint64(message.last_read_seq);
    }
    if (message.create_time !== 0) {
      writer.uint32(56).int64(message.create_time);
    }
    if (message.update_time !== 0) {
      writer.uint32(64).int64(message.update_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserConversation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserConversation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.user_id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_top = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_disturb = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.is_mute = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.last_read_seq = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.create_time = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.update_time = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserConversation {
    return {
      user_id: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      is_top: isSet(object.isTop)
        ? globalThis.Boolean(object.isTop)
        : isSet(object.is_top)
        ? globalThis.Boolean(object.is_top)
        : false,
      is_disturb: isSet(object.isDisturb)
        ? globalThis.Boolean(object.isDisturb)
        : isSet(object.is_disturb)
        ? globalThis.Boolean(object.is_disturb)
        : false,
      is_mute: isSet(object.isMute)
        ? globalThis.Boolean(object.isMute)
        : isSet(object.is_mute)
        ? globalThis.Boolean(object.is_mute)
        : false,
      last_read_seq: isSet(object.lastReadSeq)
        ? globalThis.Number(object.lastReadSeq)
        : isSet(object.last_read_seq)
        ? globalThis.Number(object.last_read_seq)
        : 0,
      create_time: isSet(object.createTime)
        ? globalThis.Number(object.createTime)
        : isSet(object.create_time)
        ? globalThis.Number(object.create_time)
        : 0,
      update_time: isSet(object.updateTime)
        ? globalThis.Number(object.updateTime)
        : isSet(object.update_time)
        ? globalThis.Number(object.update_time)
        : 0,
    };
  },

  toJSON(message: UserConversation): unknown {
    const obj: any = {};
    if (message.user_id !== 0) {
      obj.userId = Math.round(message.user_id);
    }
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.is_top !== false) {
      obj.isTop = message.is_top;
    }
    if (message.is_disturb !== false) {
      obj.isDisturb = message.is_disturb;
    }
    if (message.is_mute !== false) {
      obj.isMute = message.is_mute;
    }
    if (message.last_read_seq !== 0) {
      obj.lastReadSeq = Math.round(message.last_read_seq);
    }
    if (message.create_time !== 0) {
      obj.createTime = Math.round(message.create_time);
    }
    if (message.update_time !== 0) {
      obj.updateTime = Math.round(message.update_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserConversation>, I>>(base?: I): UserConversation {
    return UserConversation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserConversation>, I>>(object: I): UserConversation {
    const message = createBaseUserConversation();
    message.user_id = object.user_id ?? 0;
    message.conversation_id = object.conversation_id ?? "";
    message.is_top = object.is_top ?? false;
    message.is_disturb = object.is_disturb ?? false;
    message.is_mute = object.is_mute ?? false;
    message.last_read_seq = object.last_read_seq ?? 0;
    message.create_time = object.create_time ?? 0;
    message.update_time = object.update_time ?? 0;
    return message;
  },
};

function createBaseGetHistoryReq(): GetHistoryReq {
  return { conversation_id: "", start_seq: 0, end_seq: 0, limit: 0 };
}

export const GetHistoryReq: MessageFns<GetHistoryReq> = {
  encode(message: GetHistoryReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversation_id !== "") {
      writer.uint32(10).string(message.conversation_id);
    }
    if (message.start_seq !== 0) {
      writer.uint32(16).int64(message.start_seq);
    }
    if (message.end_seq !== 0) {
      writer.uint32(24).int64(message.end_seq);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.start_seq = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.end_seq = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryReq {
    return {
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      start_seq: isSet(object.startSeq)
        ? globalThis.Number(object.startSeq)
        : isSet(object.start_seq)
        ? globalThis.Number(object.start_seq)
        : 0,
      end_seq: isSet(object.endSeq)
        ? globalThis.Number(object.endSeq)
        : isSet(object.end_seq)
        ? globalThis.Number(object.end_seq)
        : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetHistoryReq): unknown {
    const obj: any = {};
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.start_seq !== 0) {
      obj.startSeq = Math.round(message.start_seq);
    }
    if (message.end_seq !== 0) {
      obj.endSeq = Math.round(message.end_seq);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryReq>, I>>(base?: I): GetHistoryReq {
    return GetHistoryReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryReq>, I>>(object: I): GetHistoryReq {
    const message = createBaseGetHistoryReq();
    message.conversation_id = object.conversation_id ?? "";
    message.start_seq = object.start_seq ?? 0;
    message.end_seq = object.end_seq ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetHistoryResp(): GetHistoryResp {
  return { list: [] };
}

export const GetHistoryResp: MessageFns<GetHistoryResp> = {
  encode(message: GetHistoryResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(Message.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryResp {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => Message.fromJSON(e)) : [] };
  },

  toJSON(message: GetHistoryResp): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => Message.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryResp>, I>>(base?: I): GetHistoryResp {
    return GetHistoryResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryResp>, I>>(object: I): GetHistoryResp {
    const message = createBaseGetHistoryResp();
    message.list = object.list?.map((e) => Message.fromPartial(e)) || [];
    return message;
  },
};

function createBaseReadMessageReq(): ReadMessageReq {
  return { conversation_id: "", seq: 0 };
}

export const ReadMessageReq: MessageFns<ReadMessageReq> = {
  encode(message: ReadMessageReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversation_id !== "") {
      writer.uint32(10).string(message.conversation_id);
    }
    if (message.seq !== 0) {
      writer.uint32(16).uint64(message.seq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadMessageReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadMessageReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadMessageReq {
    return {
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
    };
  },

  toJSON(message: ReadMessageReq): unknown {
    const obj: any = {};
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadMessageReq>, I>>(base?: I): ReadMessageReq {
    return ReadMessageReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadMessageReq>, I>>(object: I): ReadMessageReq {
    const message = createBaseReadMessageReq();
    message.conversation_id = object.conversation_id ?? "";
    message.seq = object.seq ?? 0;
    return message;
  },
};

function createBaseUpdateConversationReq(): UpdateConversationReq {
  return { conversation_id: "", is_top: 0, is_disturb: 0, is_mute: 0 };
}

export const UpdateConversationReq: MessageFns<UpdateConversationReq> = {
  encode(message: UpdateConversationReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversation_id !== "") {
      writer.uint32(10).string(message.conversation_id);
    }
    if (message.is_top !== 0) {
      writer.uint32(16).int32(message.is_top);
    }
    if (message.is_disturb !== 0) {
      writer.uint32(24).int32(message.is_disturb);
    }
    if (message.is_mute !== 0) {
      writer.uint32(32).int32(message.is_mute);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateConversationReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateConversationReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversation_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.is_top = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_disturb = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_mute = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateConversationReq {
    return {
      conversation_id: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      is_top: isSet(object.isTop)
        ? globalThis.Number(object.isTop)
        : isSet(object.is_top)
        ? globalThis.Number(object.is_top)
        : 0,
      is_disturb: isSet(object.isDisturb)
        ? globalThis.Number(object.isDisturb)
        : isSet(object.is_disturb)
        ? globalThis.Number(object.is_disturb)
        : 0,
      is_mute: isSet(object.isMute)
        ? globalThis.Number(object.isMute)
        : isSet(object.is_mute)
        ? globalThis.Number(object.is_mute)
        : 0,
    };
  },

  toJSON(message: UpdateConversationReq): unknown {
    const obj: any = {};
    if (message.conversation_id !== "") {
      obj.conversationId = message.conversation_id;
    }
    if (message.is_top !== 0) {
      obj.isTop = Math.round(message.is_top);
    }
    if (message.is_disturb !== 0) {
      obj.isDisturb = Math.round(message.is_disturb);
    }
    if (message.is_mute !== 0) {
      obj.isMute = Math.round(message.is_mute);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateConversationReq>, I>>(base?: I): UpdateConversationReq {
    return UpdateConversationReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateConversationReq>, I>>(object: I): UpdateConversationReq {
    const message = createBaseUpdateConversationReq();
    message.conversation_id = object.conversation_id ?? "";
    message.is_top = object.is_top ?? 0;
    message.is_disturb = object.is_disturb ?? 0;
    message.is_mute = object.is_mute ?? 0;
    return message;
  },
};

function createBaseGetUserConversationsResp(): GetUserConversationsResp {
  return { conversations: [] };
}

export const GetUserConversationsResp: MessageFns<GetUserConversationsResp> = {
  encode(message: GetUserConversationsResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.conversations) {
      UserConversation.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserConversationsResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserConversationsResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversations.push(UserConversation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserConversationsResp {
    return {
      conversations: globalThis.Array.isArray(object?.conversations)
        ? object.conversations.map((e: any) => UserConversation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetUserConversationsResp): unknown {
    const obj: any = {};
    if (message.conversations?.length) {
      obj.conversations = message.conversations.map((e) => UserConversation.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserConversationsResp>, I>>(base?: I): GetUserConversationsResp {
    return GetUserConversationsResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserConversationsResp>, I>>(object: I): GetUserConversationsResp {
    const message = createBaseGetUserConversationsResp();
    message.conversations = object.conversations?.map((e) => UserConversation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetUserActiveConversationsReq(): GetUserActiveConversationsReq {
  return { timestamp: 0 };
}

export const GetUserActiveConversationsReq: MessageFns<GetUserActiveConversationsReq> = {
  encode(message: GetUserActiveConversationsReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserActiveConversationsReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserActiveConversationsReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserActiveConversationsReq {
    return { timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0 };
  },

  toJSON(message: GetUserActiveConversationsReq): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserActiveConversationsReq>, I>>(base?: I): GetUserActiveConversationsReq {
    return GetUserActiveConversationsReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserActiveConversationsReq>, I>>(
    object: I,
  ): GetUserActiveConversationsReq {
    const message = createBaseGetUserActiveConversationsReq();
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseGetUserActiveConversationsResp(): GetUserActiveConversationsResp {
  return { conversations: [] };
}

export const GetUserActiveConversationsResp: MessageFns<GetUserActiveConversationsResp> = {
  encode(message: GetUserActiveConversationsResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.conversations) {
      Conversation.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserActiveConversationsResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserActiveConversationsResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversations.push(Conversation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserActiveConversationsResp {
    return {
      conversations: globalThis.Array.isArray(object?.conversations)
        ? object.conversations.map((e: any) => Conversation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetUserActiveConversationsResp): unknown {
    const obj: any = {};
    if (message.conversations?.length) {
      obj.conversations = message.conversations.map((e) => Conversation.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserActiveConversationsResp>, I>>(base?: I): GetUserActiveConversationsResp {
    return GetUserActiveConversationsResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserActiveConversationsResp>, I>>(
    object: I,
  ): GetUserActiveConversationsResp {
    const message = createBaseGetUserActiveConversationsResp();
    message.conversations = object.conversations?.map((e) => Conversation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecallMessageReq(): RecallMessageReq {
  return { msg_id: "", session_id: "" };
}

export const RecallMessageReq: MessageFns<RecallMessageReq> = {
  encode(message: RecallMessageReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg_id !== "") {
      writer.uint32(10).string(message.msg_id);
    }
    if (message.session_id !== "") {
      writer.uint32(18).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecallMessageReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecallMessageReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecallMessageReq {
    return {
      msg_id: isSet(object.msgId)
        ? globalThis.String(object.msgId)
        : isSet(object.msg_id)
        ? globalThis.String(object.msg_id)
        : "",
      session_id: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: RecallMessageReq): unknown {
    const obj: any = {};
    if (message.msg_id !== "") {
      obj.msgId = message.msg_id;
    }
    if (message.session_id !== "") {
      obj.sessionId = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecallMessageReq>, I>>(base?: I): RecallMessageReq {
    return RecallMessageReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecallMessageReq>, I>>(object: I): RecallMessageReq {
    const message = createBaseRecallMessageReq();
    message.msg_id = object.msg_id ?? "";
    message.session_id = object.session_id ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
