// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.31.1
// source: apis/llm/llm.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types.llm";

export enum Role {
  ROLE_ME = 0,
  ROLE_OTHER = 1,
  ROLE_SYSTEM = 2,
  UNRECOGNIZED = -1,
}

export function roleFromJSON(object: any): Role {
  switch (object) {
    case 0:
    case "ROLE_ME":
      return Role.ROLE_ME;
    case 1:
    case "ROLE_OTHER":
      return Role.ROLE_OTHER;
    case 2:
    case "ROLE_SYSTEM":
      return Role.ROLE_SYSTEM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Role.UNRECOGNIZED;
  }
}

export function roleToJSON(object: Role): string {
  switch (object) {
    case Role.ROLE_ME:
      return "ROLE_ME";
    case Role.ROLE_OTHER:
      return "ROLE_OTHER";
    case Role.ROLE_SYSTEM:
      return "ROLE_SYSTEM";
    case Role.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ChatMessage {
  role: Role;
  content: string;
}

export interface SuggestRequest {
  history: ChatMessage[];
}

export interface SuggestResponse {
  reply: string[];
}

function createBaseChatMessage(): ChatMessage {
  return { role: 0, content: "" };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.role !== 0) {
      writer.uint32(8).int32(message.role);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMessage {
    return {
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: ChatMessage): unknown {
    const obj: any = {};
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.role = object.role ?? 0;
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseSuggestRequest(): SuggestRequest {
  return { history: [] };
}

export const SuggestRequest: MessageFns<SuggestRequest> = {
  encode(message: SuggestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.history) {
      ChatMessage.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SuggestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSuggestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.history.push(ChatMessage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SuggestRequest {
    return {
      history: globalThis.Array.isArray(object?.history) ? object.history.map((e: any) => ChatMessage.fromJSON(e)) : [],
    };
  },

  toJSON(message: SuggestRequest): unknown {
    const obj: any = {};
    if (message.history?.length) {
      obj.history = message.history.map((e) => ChatMessage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SuggestRequest>, I>>(base?: I): SuggestRequest {
    return SuggestRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SuggestRequest>, I>>(object: I): SuggestRequest {
    const message = createBaseSuggestRequest();
    message.history = object.history?.map((e) => ChatMessage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSuggestResponse(): SuggestResponse {
  return { reply: [] };
}

export const SuggestResponse: MessageFns<SuggestResponse> = {
  encode(message: SuggestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.reply) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SuggestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSuggestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reply.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SuggestResponse {
    return { reply: globalThis.Array.isArray(object?.reply) ? object.reply.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: SuggestResponse): unknown {
    const obj: any = {};
    if (message.reply?.length) {
      obj.reply = message.reply;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SuggestResponse>, I>>(base?: I): SuggestResponse {
    return SuggestResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SuggestResponse>, I>>(object: I): SuggestResponse {
    const message = createBaseSuggestResponse();
    message.reply = object.reply?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
